### ISSUE TITLE
VB -> C#: don't add unnecessary whitespace between label and empty statement

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1065]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see a label followed by a line break followed by lots of spaces followed by a semicolon, like this:
```cs
            ProcError:
                ;
```

**Describe the solution you'd like**
I'd like it to be more compact, like this:
```cs
            ProcError:;
```

**Describe alternatives you've considered**
Search&Replace pass is viable, but slightly dangerous in case it'll hit some string constants or comments.
For reference:
Search: `:\r\n\s+;`
Replace: `:;`

**Additional context**
None

**Comment by GrahamTheCoder** [comment]
I think filtering out empty statements at the end of ConvertStatements would be a good approach

**Comment by TymurGubayev** [comment]
but the `;` is an empty statement, and IMO it's better to keep them because otherwise we might have to deal with the interesting way C# labels are syntactically structured:

```cs
public void M() {
    l1:
    l2:
    l3:
    ;
}
```
https://sharplab.io/#v2:C4LghgzsA0AmIGoA+ABATARgLACgUGYACdQgYUIG9dCbiiUAWQgWQAoBKS62ngGwxDceNXmkE5htXvnGSaAbiGEAvrmVA===

The body block here only has a single `LabeledStatement`, which in turn contains another nested `LabeledStatement` and so on.

**Comment by GrahamTheCoder** [comment]
Ah yeah, it's not valid to have a label without a following statement

In which case I'll close the issue since I feel the current output is fine and personal preferences will always need to be fixed with a code formatter (or regex in your case) after the fact. There are some things that'd make me reconsider this, like if it was a really common pattern and looked bad in a larger context, but I suggest we focus on the many other issues. Thanks!

**Comment by TymurGubayev** [comment]
Understandable, and the regex is fine in most cases.

Thanks for all the work you are doing!
