### ISSUE TITLE
VB -> C#: Differing namespace rules in C#

### ISSUE THREAD

**Issue by GrahamTheCoder** [icsharpcode/CodeConverter#107]
A user review said "C# files require namespaces, but the tool did not add them" (see Tony Waterman's [review](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter#review-details))

In general a C# doesn't need to be explicitly in a namespace, but I think there likely are some differences between namespaces to be investigated and fixed. Any source code that ends up not compiling due to needing a namespace would be much appreciated.

[Type promotion](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/declared-elements/type-promotion) in VB may cause some unexpected errors in conversion

**Comment by CoderNate** [comment]
There are a few differences in VB.
1)  Type promotion, like you said.  You could use the C# 6 "using static" for that.
2)  The "Root Namespace" defined in the project's properties gets automatically inserted at the beginning of every top-level declaration in the source code.  So if the top level item for a file is a namespace declaration, the project's root namespace will be added to the beginning.  If the top level is a module or a class, the root namespace will be added to that.  In order to to declare something outside of the root namespace you can start it with "Global" like Global.Some.Namespace.
3)  VB lets you declare partially-qualified types based on namespaces you've imported:
```vbnet
Imports System.Collections
...
Dim d As Specialized.OrderedDictionary
```
You would have to do this in C#:
```C#
using Specialized = System.Collections.Specialized;
...
Specialized.OrdereredDictionary d;
```

**Comment by GrahamTheCoder** [comment]
1. `QualifyNode` attempts to deal with point 2, by fully qualifying partially qualified namespaces - though it's a bit clunky and there will be some bugs.
2. Is probably not dealt with by the above. It could be extended to do so, or we could use the `using static` approach. I'm happy with either.
3. Your PR #150 deals with it entirely 👍

**Comment by GrahamTheCoder** [comment]
@CoderNate Looking at `QualifyNode` now, can you see any other cases that might not be handled or deserve a test case before we can close this issue?

**Comment by CoderNate** [comment]
I just created pull request #156 that fixes a bug I encountered.  I mentioned in the comment on that pull request that it might be good to have a test for nested classes.  But otherwise I can't think of anything else.  Nice work!

**Comment by GrahamTheCoder** [comment]
I believe this is now fixed 🎉
