### ISSUE TITLE
VB -> C#: Module named `[Global]` causes strange effects

### ISSUE THREAD

**Issue by TymurGubayev** [icsharpcode/CodeConverter#1093]
### VB.Net input code
```vbnet
Namespace Global.TestProject
    Public Module [Global]
        Sub S()
            S()
        End Sub
    End Module
End Namespace
```

### Erroneous output
```C#
namespace TestProject
{
    public static class Global
    {
        public static void S()
        {
            Global::TestProject.Global.S();
        }
    }
}
```

### Expected output
```C#
namespace TestProject
{
    public static class Global
    {
        public static void S()
        {
            S();
        }
    }
}
```

### Details
* Product in use: VS extension
* Version in use: 5143c08297ae65cb7490ae768645f61131bf96be
* Did you see it working in a previous version, which? no
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Is the workaround just to find/replace "Global::" with "global::"?

Unless there's a common pattern for naming a module Global (which seems to me a pretty odd thing to do given it needs escaping since it's reserved), I'm content with a find-replace being needed in this very special case that may never arise again.

**Comment by TymurGubayev** [comment]
yep, some search&replace resolved it I think.
