### ISSUE TITLE
Project conversion converts proj file then pauses for a long time with no feedback

### ISSUE THREAD

**Issue by TimPurdum** [icsharpcode/CodeConverter#132]
### Erroneous output
Right-click on VB project, select `Convert to C#` converts just .vbproj file to .csproj

### Expected output
Right-click on VB project, select `Convert to C#` converts all project files.

### Details
Product in use: VS 2017 Extension

Version in use: 5.7.0.0

There is very little documentation, so I may be missing something obvious here. I know older versions were capable of converting a project. Currently, I seem to be limited to doing each file individually.

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Your intuition for what should happen is correct. i.e. When you convert a vbproj it will:
* Create a converted .csproj alongside it
* Create a converted .cs file for each .vb file within that project
* Ask whether to update the solution file and any referencing projects.

The only exceptions to this that come to mind are:
* Any files outside the solution folder aren't converted - currently the tool doesn't warn about these ignored files - I'll add something into the output.
  * Specifically it does [this](https://github.com/icsharpcode/CodeConverter/blob/master/ICSharpCode.CodeConverter/Shared/ProjectConversion.cs#L28)  which also has potential for failure if the paths aren't normalized the same way by Roslyn somehow.
* Any files containing vb but with other extensions aren't converted. e.g. aspx, vbhtml. This is mentioned in https://github.com/icsharpcode/CodeConverter/issues/16

I've just manually verified this works as described on two test projects using the 5.7.0.0 extension.
* To troubleshoot this case further it'd be useful to see the contents of the Code Converter output window (click cancel when asked to write out solution file changes, otherwise it gets cleared...I'll fix that some time).
* Contents of the vbproj (if it's an open source project then just link to the repo and I'll try it out myself).

**Comment by TimPurdum** [comment]
Thanks for your response. I get no dialog when clicking `Convert to C#`, it goes straight to the output window with just this:

`--------------------------------------------------------------------------------
Writing converted files to disk:
* filepath\projectName.csproj------------------------------------`

The created `csproj` looks good, but the `.cs` files are not created. I unfortunately can't share the whole project file, but below is some of the opening. 
``` <?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid></ProjectGuid>
    <OutputType>Library</OutputType>
    <MyType>Windows</MyType>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <SccProjectName>
    </SccProjectName>
    <SccLocalPath>
    </SccLocalPath>
    <SccAuxPath>
    </SccAuxPath>
    <SccProvider>
    </SccProvider>
    <TargetFrameworkProfile />
  </PropertyGroup>

**Comment by GrahamTheCoder** [comment]
Interesting. Since there's no error, the most likely cause is that:
* It's detecting no syntax trees - this could happen if there was an issue with the project file or it used variables in the file names
* The project files do not start with the solution directory.

To narrow the possible causes, could you create a brand new library vbproj + solution and see if it converts that ok (to just an empty class or whatever)?
* If it does, could you try copy-pasting your files into that project folder, clicking "show all files" in the solution explorer, selecting/including them all, then try converting the project again (the references won't be right, but it should at least have a slightly ill-fated attempt at the conversion).
  * If that generates some .cs files with any success, have a look at how the project file differs from your own (other than the references), and see if you can isolate the thing which causes the problem (it may also be relevant to look at any projects you've previously converted successfully and whether they can still be converted by this version).
* Otherwise, it'd be helpful to know which Visual Studio version you're using, and if you recall which extension version last worked for you (roughly speaking).

**Comment by GrahamTheCoder** [comment]
There's a chance this was a symptom that will be fixed by #135.
If so, it'd probably mean some conversion error messages are getting swallowed somewhere.

**Comment by PaulVrugt** [comment]
I had the same issue, it turned out I was simply too impatient. After waiting for a long time it started converting the files too. Might be a good idea to let the user know something is happening in the background after converting the project file

**Comment by GrahamTheCoder** [comment]
Thanks for getting in touch, it all makes sense now. It compiles any other referenced projects of the same language, and gives no feedback about doing so. If the project being converted references lots of other projects (or large projects, or running on a slow machine, etc.), it could take a long time with no feedback.

Should be an easy fix, I'll try to get it done soon. I think there's also some caching I might be able to do to slightly speed up that time - I'll look into that afterwards.
