### ISSUE TITLE
Telerik converter do not work 

### ISSUE THREAD

**Issue by Polarwolf3** [icsharpcode/CodeConverter#162]
I try to use the telerik web converter today and I do not know why but it do not convert anything. The day before yesterday it works. I also ask a college to test ist but it also do not work on his workplace. There is no error message or something, so I really do not know where the Problem come from. I try "C# -> VB: " and "VB -> C#: " .

I hope someone can help!

**Comment by christophwille** [comment]
Although http://converter.telerik.com/Home/About states that errors should be reported here, it didn't mean "generic" service availability errors, but conversion error (language constructs that are converted the wrong way or not at all). We do not operate that service, ours is located at https://codeconverter.icsharpcode.net/

**Comment by GrahamTheCoder** [comment]
Closing this since there's nothing we can do about Telerik's site being down - we aren't affiliated with them, they just use our conversion library. Hopefully you can make use of our [Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter) or [Online snippet converter](https://codeconverter.icsharpcode.net/) instead. If not, please do raise issues here for either of those.
