### ISSUE TITLE
Question: about byte array

### ISSUE THREAD

**Issue by shaneshuford** [icsharpcode/CodeConverter#163]
Was something changed recently that would effect the way the codeconverter converts byte code arrays from C# to vb.net? It seems to output something different than it did before,  but the tool on carlosag.net still outputs the code the way telerik's tool once did.

**Comment by GrahamTheCoder** [comment]
Thanks for getting in touch. There was a PR that changed how array literals work reasonably recently, which *could* be related: https://github.com/icsharpcode/CodeConverter/pull/140/files#diff-147671de17f06092e1edbbc8ab7f5826R499

Is the new way it's converted causing an issue? Please give some example code (even just a single line) that converts differently and say what it used to do, then we can investigate further.

**Comment by shaneshuford** [comment]
To be completely honest with you, i'm not sure if i understand exactly what is going on here with the change. I use a tool to convert some code into a byte array formatted for C#. i then used this to convert it to vb.net.

**C# Input:**
`byte[] buf = new byte[632] {
	0xb8,0x82,0xc0,0xb7,0x51,0xdb,0xc7,0xd9,0x74,0x24,0xf4,0x5a,0x29,0xc9,0xb1,
	0x98,0x31,0x42,0x13,0x83,0xc2,0x04,0x03,0x42,0x8d,0x22,0x42,0xeb,0xa0,0xf3,
	0x41,0x93,0x1f,0x35,0x40,0xd8,0xbb,0x4e,0x2e,0x12,0x0a,0x1f,0x40,0xd7,0x49,
	0x64,0x52,0x8d,0x41,0x66,0xc1,0x3d,0xb2,0xcc,0xbd,0xd6,0x3d,0xcc,0x13,0xe4
};`

**vb.net Old Output:**
Dim buf() As Byte = New Byte() {184, 130, 192, 183, 81, 219, 199, 217, 116, 36, 244, 90, 41, 201, 177, 152, 49, 66, 19, 131, 194, 4, 3, 66, 141, 34, 66, 235, 160, 243, 65, 147, 31, 53, 64, 216, 187, 78, 46, 18, 10, 31, 64, 215, 73, 100, 82, 141, 65, 102, 193, 61, 178, 204, 189, 214, 61, 204, 19, 228}

**vb.net New Output:**
`Dim buf As Byte() = New Byte(631) {&Hb8, &H82, &Hc0, &Hb7, &H51, &Hdb, &Hc7, &Hd9, &H74, &H24, &Hf4, &H5a, &H29, &Hc9, &Hb1, &H98, &H31, &H42, &H13, &H83, &Hc2, &H04, &H03, &H42, &H8D, &H22, &H42, &Heb, &Ha0, &Hf3, &H41, &H93, &H1F, &H35, &H40, &Hd8, &Hbb, &H4e, &H2e, &H12, &H0a, &H1F, &H40, &Hd7, &H49, &H64, &H52, &H8D, &H41, &H66, &Hc1, &H3D, &Hb2, &Hcc, &HbD, &Hd6, &H3D, &Hcc, &H13, &He4}`

**Comment by GrahamTheCoder** [comment]
Ah awesome, the example clarifies things totally! Nothing has specifically changed about arrays, but something has changed about constants/literals. This is completely intentional, since that's [how Visual Basic .NET represents hex literals](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/data-types/type-characters#hexadecimal-binary-and-octal-literals). So 0xb8, 184 and &Hb8 are all the same number. The idea is to make the output more closely look like the input (basically `0x`, the csharp hex prefix is replaced with `&H`, the vb hex prefix).

If you didn't want that, you could use the integers in the input directly like so:
`byte[] buf = new byte[] { 184 }`
converts to
`Dim buf As Byte() = New Byte() {184}`

Let me know if the change is causing any kind issue (e.g. compilation issue) and I'll reopen this, but as far as I'm aware it should be completely *equivalent* to the old output. Apologies if you were previously using the tool as a converter between hex and decimal. If you put each of the values on a new line then you can convert them all together using a tool like this https://www.browserling.com/tools/hex-to-dec (note: not affiliated with this site in any way)
