### ISSUE TITLE
Add editor context menu to "Paste as VB"/"Paste as C#"

### ISSUE THREAD

**Issue by beppe9000** [icsharpcode/CodeConverter#245]
I used to use the PasteAs extension, but it's for VS 2005, so it's outdated.
Does CodeConverter have that feature? I can't find it, so in the doubt I suggest it as a feature.

**Comment by GrahamTheCoder** [comment]
There's an option you can enable so that the conversion result is copied to the clipboard:
https://github.com/icsharpcode/CodeConverter/issues/37#issuecomment-385810811
That might help you a bit.

However, I can see that if you want to copy something from a website like stack overflow and then paste it straight into your project of a different language, the feature you suggest could save some hassle.

I'm very happy to take a PR to add it. It should be reasonably easy to do - just add an extra menu item, register it in the command, and call the existing ConvertText method using the clipboard as source (copying from the way the other ones work). Are you interested in implementing it?

**Comment by beppe9000** [comment]
I never worked with vs extensions, but can try :)

**Comment by GrahamTheCoder** [comment]
Great 😄 I know it can be hard to figure out what's happening at the top level of a VS extension particularly, so here's a few pointers to relevant bits of code.

The most extension related part is duplicating the context menu entries in this file:
https://github.com/icsharpcode/CodeConverter/blob/master/Vsix/REConverterPackage.vsct#L31
https://github.com/icsharpcode/CodeConverter/blob/master/Vsix/REConverterPackage.vsct#L65

Then if you see where the existing command is used (note how the id defined matches the one defined at the bottom of the vsct file), it's a case of setting up your own handlers.
https://github.com/icsharpcode/CodeConverter/blob/e008f14d116bdb1619607c185cae8ab1e3e40627/Vsix/ConvertVBToCSCommand.cs#L23
https://github.com/icsharpcode/CodeConverter/blob/e008f14d116bdb1619607c185cae8ab1e3e40627/Vsix/ConvertCSToVBCommand.cs#L26

There's a handler for deciding if the command is visible, and one for doing the conversion (for each direction of language conversion):
https://github.com/icsharpcode/CodeConverter/blob/e008f14d116bdb1619607c185cae8ab1e3e40627/Vsix/ConvertVBToCSCommand.cs#L142
https://github.com/icsharpcode/CodeConverter/blob/e008f14d116bdb1619607c185cae8ab1e3e40627/Vsix/ConvertCSToVBCommand.cs#L145

You'll probably need to write a new public wrapper that calls through to this method in the CodeConversion class:
https://github.com/icsharpcode/CodeConverter/blob/325ae7a5146bd4e2afd9ea3c396c554dcc639d12/Vsix/CodeConversion.cs#L238

Let me know if you want any more pointers, feel free to PR something before it's fully formed so it's easy to make comments on specific bits of code.

**Comment by beppe9000** [comment]
Thanks for the support! I will update this issue once I'm done or stuck :)

**Comment by GrahamTheCoder** [comment]
I've just discovered there's an existing Paste Special menu where it'd be really great to integrate this behaviour
https://developercommunity.visualstudio.com/idea/851239/please-add-paste-special-to-the-context-menu.html

**Comment by GrahamTheCoder** [comment]
Implemented in #622
