### ISSUE TITLE
VB -> C#: XmlElement conversion not implemented for non-literals

### ISSUE THREAD

**Issue by Rubicen** [icsharpcode/CodeConverter#253]
### Input code
```vbnet
Dim element As XElement = <SetAttribute XPath=<%= entry.Code %>></SetAttribute>
```

### Erroneous output
```C#
XElement element = XElement.Parse("<SetAttribute XPath=<%= entry.Code %>></SetAttribute>");
```

### Expected output
```C#
XElement element = new XElement("SetAttribute", new XAttribute("XPath", entry.Code));
```

### Details
Product in use: e.g. web converter

Version in use: newest

Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by BobFrankston** [comment]
Handling embedded XML is one of the reasons for using VB over C# so converting such code makes it easier to move on.

**Comment by GrahamTheCoder** [comment]
Thanks both for raising this, and especially for the example with expected output. My apologies for not commenting sooner.

Looking at [the docs](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/xml/how-to-modify-xml-literals) this could easily be a big task to implement, but hopefully it'll be possible in stages, starting with simple literal support then later handling various inline replacements, and the query/modify/insert syntax.

Ideally every possible operation doesn't need to be a hardcoded syntax transformation - there will hopefully be a way to generalize our approach, by making use of the semantic model and other parts of the API. The first step of that is to put a few examples into the converter and see what level of information is available from the semantic model.

**Comment by GrahamTheCoder** [comment]
At a quick look, there are 21 syntax constructs to convert. If we can't find a consistent way to convert them (especially one that keeps roughly in line with the currently parsed structure), then that will be rather tedious to implement.

An example of part of this that (at least on the surface) looks consistent and easy because the structure is the same, and thus the existing per-node visiting conversion works very naturally:
```vbnet
For Each book In From element In catalog.<Catalog>.<Book>
  book.<Price>.Value = book.<Price>.Value * 1.05
Next
```

```csharp
foreach (XElement book in catalog.Elements("Catalog").Elements("Book")) 
{
   book.Element("Price").Value = Conversions.ToDecimal(book.Element("Price").Value) * (decimal) 1.05;
}
```

**Comment by BobFrankston** [comment]
Also, if I understand the rules correctly
```
   dim a = el.@atr
```
becomes
```
  var a = el?.attribute("atr")?.value
```

**Comment by GrahamTheCoder** [comment]
Description edit: I've updated the erroneous output for the current release, and added an alternative expected output

**Comment by Noah1989** [comment]
I am starting on this issue now.

**Comment by BobFrankston** [comment]
as an FYI {} by itself was not enough --  you need to do the proper escape codes. String interpolation in C# has a feature similar to tagged strings in JavaScript -- you can say htmlescape`<p>${foo}</p>` so that if foo is "a>b" it becomes "a&gt;b". I don't remember it offhand but you can do something similar in C#.
