### ISSUE TITLE
Make it more obvious how to use the extension on first run

### ISSUE THREAD

**Issue by mggohil** [icsharpcode/CodeConverter#257]
How to Use this tool , i have downloaded the tool. Not able to convert the project.

**Comment by GrahamTheCoder** [comment]
Please read https://github.com/icsharpcode/CodeConverter/wiki and use it for context to describe what you are trying to do.

E.g. Screenshot of a context menu missing the options you expect, and some information about the project you wish to convert.

**Comment by GrahamTheCoder** [comment]
There isn't a whole lot of information here, but it does echo some previous comments: People aren't sure what to do after installation. This is exacerbated when their particular project isn't supported and the tool just silently hides away all its menus.

I'll leave this here to gather other feedback and suggestions on how to improve this area.

**Comment by GrahamTheCoder** [comment]
Since this feedback, I've made the context menus appear instantly on VS load (before the extension loads), so there's no chance of someone missing it due to the extension not having loaded. I believe this will help some people, so I'll close this issue.

There is much more that could be done, but I'll wait for feedback on specific confusion.
