### ISSUE TITLE
VB -> C#: Incorrect class prefix for builtin date functions

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#261]
### Input code
```vbnet
Public Class Class1
    Sub Foo()
        Dim x = DateAdd("m", 5, Now)
    End Sub
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        var x = DateTime.DateAdd("m", 5, DateTime.Now);
    }
}
```

### Expected output
```c#
public class Class1
{
    public void Foo()
    {
        var x = DateAndTime.DateAdd("m", 5, DateTime.Now);
    }
}

```

### Details
Product in use: e.g. VS extension

Version in use: e.g. 6.6.0

Built in date functions are in the `DateAndTime` class, not `DateTime`.

**Comment by GrahamTheCoder** [comment]
At the moment I think there's a very blanket attempt to make things use DateTime rather than DateAndTime. It was in a very early effort to head in the direction of https://github.com/icsharpcode/CodeConverter/issues/174
Perhaps a nice improvement here would be to check for the existence of a DateTime symbol, and fall back on using the DateAndTime one.
