### ISSUE TITLE
VB -> C#: Add/remove parenthesis

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#265]
### Input code
```vbnet
Public Class Class1
    Sub Foo()
        Dim x = Bar
    End Sub

    Function Bar() As Integer
        Return 1
    End Function
End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        var x = Bar;
    }

    public int Bar()
    {
        return 1;
    }
}
```

### Expected output
```c#
public class Class1
{
    public void Foo()
    {
        var x = Bar();
    }

    public int Bar()
    {
        return 1;
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.6.0

In VB, parenthesis are optional for method calls - they need to be added when converting to C#.

The reverse is also true - VB allows parenthesis for properties, where C# doesn't.

**Comment by GrahamTheCoder** [comment]
I'm surprised to see it fail in such a simple case, I seem to remember there's some code for dealing with it when it's parsed as an empty argument list. Perhaps it's coming out as a different syntax structure.

I was not aware property calls could have parentheses so that's unlikely to be covered anywhere so far.
