### ISSUE TITLE
VB -> C#: Method call with unknown class uses square brackets

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#266]
### Input code
```vbnet
Public Class Class1
    Sub Foo()
        Bar(Nothing)
    End Sub

    Private Function Bar(x As SomeClass) As SomeClass
        Return x
    End Function

End Class
```

### Erroneous output
```c#
public class Class1
{
    public void Foo()
    {
        Bar[null/* TODO Change to default(_) if this is not a reference type */];
    }

    private SomeClass Bar(SomeClass x)
    {
        return x;
    }
}
```

### Expected output
```c#
public class Class1
{
    public void Foo()
    {
        Bar(null);
    }

    private SomeClass Bar(SomeClass x)
    {
        return x;
    }
}
```

### Details
Product in use: VS extension

Version in use: 6.6.0

Even without `SomeClass` being available, it should still treat `Bar()` as a method call.

**Comment by GrahamTheCoder** [comment]
Yep, agreed. There is already some attempt to handle missing information for this, but this case should take precedence over the guesswork done at this point:
https://github.com/icsharpcode/CodeConverter/blob/28e5607c121d05a0da710d4eea5c94e9457db26b/ICSharpCode.CodeConverter/CSharp/NodesVisitor.cs#L1455

**Comment by mrmonday** [comment]
We could actually use C# 7.1 syntax for that, which allows for `default`, without a type.

**Comment by GrahamTheCoder** [comment]
As a very general rule I basically aim to support the current and previous major versions of things where it's convenient to do so. I think here it's pretty easily possible to stay backwards compatible, so probably worth doing since it's quite a common case.
Within this codebase of course we're free to use the latest stable version (i.e. whatever we can reasonably expect contributors to upgrade to).
