### ISSUE TITLE
Comment lines lost

### ISSUE THREAD

**Issue by SynerSoft** [icsharpcode/CodeConverter#27]
It would be helpful if the comments were not stripped out of the converted code.  When things don't work and one is trying to compare the before and after, the comments would be especially helpful.

Thanks!

**Comment by GrahamTheCoder** [comment]
There are a few difficulties to getting this exactly right, but I've recently merged a first attempt in https://github.com/icsharpcode/CodeConverter/pull/24

Please feel free to try compiling and running the latest build from master and let me know if it behaves better than the currently released version. I'll close this issue since the work has been done, and release it very soon hopefully.
