### ISSUE TITLE
Show AppVeyor Status in pull requests

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#301]
It would be great if the AppVeyor status showed in pull requests.

Status can be seen here, but not on the PR itself - https://ci.appveyor.com/project/icsharpcode/codeconverter/history

**Comment by christophwille** [comment]
AppVeyor is active for pull_request and push, see https://ci.appveyor.com/project/icsharpcode/codeconverter/history

**Comment by mrmonday** [comment]
Thanks. I've updated the issue - didn't realise we already had CI, it wasn't visible!

You can set it up to show on PRs, eg. https://github.com/libpnet/libpnet/pull/363#partial-pull-merging (ctrl-f for "check", or scroll to the bottom).

I can't remember how I set this up for libpnet, I assume I clicked through some UI on AppVeyor's side.

**Comment by GrahamTheCoder** [comment]
It still works for refactoring essentials [e.g.](https://github.com/icsharpcode/RefactoringEssentials/pull/385), but has never worked on this repo since it was split out. Probably just needs a webhook approximately here to have the right settings the same as refactoring essentials:
https://github.com/icsharpcode/CodeConverter/settings/hooks
I don't have permission to see the page, @christophwille - are you able to check or remove and readd that?

**Comment by christophwille** [comment]
I have asked @dgrunwald what the magic ist

**Comment by dgrunwald** [comment]
I don't remember any magic.

Maybe some permission problem? Setting statuses requires some form of write access. I don't remember how I set that up with AppVeyor, I guess there was some OAuth stuff involved...

**Comment by christophwille** [comment]
Thanks, that was exactly the hint I needed - the build server GH account had only read access, whereas in all other repos it had write.
