### ISSUE TITLE
VB -> C#: Conditional method calls with ByRef parameters

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#310]
Via #307.

### Input code
```vbnet
If False AndAlso MethodWithByRef(MethodWithSideEffects()) Then
    DoSomething()
End If
```

### Erroneous output
```c#
var arg = MethodWithSideEffects();
if (false && MethodWithByRef(ref arg))
{
    DoSomething();
}
```

### Expected output

Unsure. Maybe something like:

```c#
Func<bool> arg = () => { var arg = MethodWithSideEffects(); MethodWithByRef(ref arg); };
if (false && arg())
{
    DoSomething();
}
```

**Comment by GrahamTheCoder** [comment]
Yeah that's a bit like happens for inline assignment for c# to vb

**Comment by GrahamTheCoder** [comment]
Consolidating into 324 which has a suggested implementation which will fix this

**Comment by GrahamTheCoder** [comment]
Plan for #324 changed, separating this out again.

**Comment by GrahamTheCoder** [comment]
Looking at [the IL / C# decompilation](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUPQAoCuEwAlgMaEDCwAhviIBZUgBVKFPoPz16hBYUbZ2YflSXZM6SnlKbthAIJFkAOyoBzXfMXLV6yoQBizM51ztMZwmP4BrSQAlSgAzAAoAIVIQ0MIwbAgxCmNTC0prbABKW0VFBKSUgF54xOTcQnhCAEZcvMIQ3GZsHzFsZko6gFEzGBc3Dy8zOTo8+zUNYlZCAFV8YLDw/ExUSkjMTGBUwnXNyn4zKEJl1fMKk0IzjN0c0fqFZDjqgDZCAD5jlcozwgB5bC6wHmvgCCwiym0t3u9x43mWwEoADoAOoqKgAGXYZko4WqWTydTygOBj0+q12WyMvSM6OWIMC+Fi4Qh6Ch0LyJ2+FkqJVqd3uxM6/PZvDhexRaMomOx4QAzGyBb1LqFukqphB6D0+tIhEA===), it's just expressed by hoisting the conditions out the front of the loop: 
(Prop with theoretical potential side effects in this example to also cover #324)
```vbnet

Imports System

Public Class MyTestClass

    Private Property Prop As Integer
    Private Function TakesRef(ByRef vrbTst As Integer) As Boolean
        vrbTst = vrbTst + 1
        Return True
    End Function

    Private Sub UsesRef(someBool As Boolean, someInt As Integer)
        If 16 > someInt OrElse TakesRef(Prop)
            Console.WriteLine(1)    
        Else If someBool AndALso TakesRef(Prop)
            someInt += 1
        Else
            Console.WriteLine(3)
        End If
    End Sub
End Class
```

```csharp

    private void UsesRef(bool someBool, int someInt)
    {
        bool cond = true;
        if (!(16 > someInt))
        {
            int vrbTst = Prop;
            cond = TakesRef(ref vrbTst);
            Prop = vrbTst;
        }
        if (cond)
        {
            Console.WriteLine(1);
        }
        else 
        {
            bool cond1 = false;
            if (someBool)
            {
                int vrbTst = Prop;
                cond1 = TakesRef(ref vrbTst);
                Prop = vrbTst;
            }
            if (cond1)
            {
                someInt += 1;
            }
            else
            {
                Console.WriteLine(3);
            }
        }
    }
```

Beautifully hackily horrendous alternative that's shorter and avoids the allocation:
```csharp
        int argvrbTst;
        int argvrbTst1;
        if (16 > someInt || (argvrbTst = Prop, TakesRef(ref argvrbTst), Prop = argvrbTst).Item2)
        {
            Console.WriteLine(1);
        }
```

Local functions alternative which I'm pretty certain will avoid allocation still since they use structs if not exposed outside the method ([demo here](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFDKgZgAQAcCGAnAFwEscAbDWDAWQE8AVAUwGcCBhUnJp5Ab2QwHY8RAG44CDDEQB2BDAAU8AeywYeGAOYMCAbgxNtegL7J+grMLESMAIyVLydHAGtmAJQYAzABRQ4ABn0CPAAaCgCgvBgwvC8pWQwRPBs6FgBKMwE+JEFcxOTUuQBefJSWDDAMOB1MvKgAdgxggFcGGpzBExRu3ItRcUkoABYMAFUDJg9PGG87B30lAFsGACF7UjCZOSYlhgBJWQyOrNrcsTxIjBK4ADo6JQBlYJkNbzT2vME5xxd3L0UVL4Iiwomk1Il8Bh8BokmVigplFg9OcMLF4U5XJMvN4QWEQdFUXFobDCu8ESorlC8DCCiw9A1CboMF1PgIiJ4MN44AA2DAAPgWywOcggEAwGL+ngBWBxwTSR1ZalOrL8AE4ue9lQIWayGKQDFIOTjdmt5gAyM3i35YqWI2V4eVapXHRWXMAlABEaA9H1dAh2QoS7qqvs+Os+eoMTuyfoEau8aE1Lty4eZyCMQA==)):
```csharp
        bool TakesRefProp() { var argvrbTst = Prop; var ret = TakesRef(ref argvrbTst); Prop = argvrbTst; return ret; }
        if (16 > someInt || TakesRefProp())
```

So yep I think the ideal is exactly what you said in the first place, but with a local function instead of a lambda.
