### ISSUE TITLE
VB -> C#: Array initialization adds wrong curly brackets.

### ISSUE THREAD

**Issue by fabienDaou** [icsharpcode/CodeConverter#355]
Array initialization adds wrong curly brackets. This results in a compilation error.

### Input code
```vbnet
Public Class VisualBasicClass
  Public Sub Stuff()
    Dim strs = New String(2) {}
  End Sub
End Class
```

### Erroneous output
```C#
public class VisualBasicClass
{
    public void Stuff()
    {
        var strs = new string[3] { }; // Error: An array initializer of length '3' is expected
    }
}
```

### Expected output
```C#
public class VisualBasicClass
{
    public void Stuff()
    {
        var strs = new string[3];
    }
}
```

### Details
Product in use: e.g. both
Version in use: e.g. 7.0.0.0

**Comment by fabienDaou** [comment]
Looking at this one, seems pretty easy.

**Comment by GrahamTheCoder** [comment]
Thanks!

I found a test case that's broken, but it's not 100% related and I wanted to get your branch merged since I think it's an improvement already. Here's the test case if you're interested: https://github.com/icsharpcode/CodeConverter/compare/355/related-test?expand=1#diff-ab8f9b4966dbff4521cf21456fd2985fR559

**Comment by fabienDaou** [comment]
Ok I was not aware about this syntax, I'll provide a PR with a fix.

**Comment by GrahamTheCoder** [comment]
Closing this issue since your fix covered it and https://github.com/icsharpcode/CodeConverter/issues/364 covers the related part I mentioned.
