### ISSUE TITLE
All visual basic classes are partial classes

### ISSUE THREAD

**Issue by tverweij** [icsharpcode/CodeConverter#368]
In VB I can make a class partial by adding the partial keyword.
But this keyword is (kind of) optional 

### Input code

```
Public Class x
    Public a As Integer
End Class

Public Partial Class x
    Public  b As Integer
End Class

```
### Erroneous output
This translates 100% correct as long as they are in the same module.
But If I have them in 2 modules, it needs 2 translations, where the first one is not translated to partial.

### Expected output
To be safe, add partial to any class, because this is mandatory for c# and not for VB, it can give a compile error if not added, while it just works as it is added.

**Comment by GrahamTheCoder** [comment]
Thanks for reporting. When you talk about two modules, are you talking about VB module types, or Dot Net modules (which tend to align with assembly and project boundaries)? The first one seems surprising, but I didn't think the second was possible.

**Comment by tverweij** [comment]
I was talking about separate code files .

**Comment by GrahamTheCoder** [comment]
Ah interesting. I thought I'd already fixed that issue in https://github.com/icsharpcode/CodeConverter/commit/a43b0400b27a6a946299b227fe3416c9ed66779c
Obviously it only works in the same file, so I'll add a project-level test and fix it properly!

**Comment by GrahamTheCoder** [comment]
I've now realized you must be talking about using the web converter to convert one file at a time - I've made the change you described for that case.

 It'd be technically possible to provide the functionality to convert multiple files/projects on the web converter, but there are a lot of difficulties like sdk versions and people referencing a private nuget feed etc. So I'm trying to encourage people to use the VS extension. If you have time, I'd love to know:
* Did you know you'd get a worse quality conversion using the web converter due to the lack of project context?
* What's the biggest blocker stopping you using the VS extension?

Thanks!
