### ISSUE TITLE
VB -> C#: Add special cases for idiomatic conversions

### ISSUE THREAD

**Issue by EdHonnegan** [icsharpcode/CodeConverter#388]
Please prefix the issue title with either "C# -> VB: " or "VB -> C#: " if relevant

### Input code
```vbnet
Dim wordArray As String() = csvString.Split(CChar(","))
```

### Erroneous output
```c#
var wordArray = csvString.Split(Conversions.ToChar(","));
```
Conversions.ToChar() wasn't recognised in C# - it appears that the correct method is Convert.ToChar()

### Expected output
```c#
var wordArray = csvString.Split(Convert.ToChar(","));
```

### Details
* Product in use: web converter: https://codeconverter.icsharpcode.net/
© 2015-2019 - Code Converter by https://github.com/icsharpcode/CodeConverter/ - Version 7.1.0.0

**Comment by GrahamTheCoder** [comment]
Thanks for raising the issue. The output you suggest is more idiomatic for C#, but its behaviour may differ in some cases (though not in this simple case). The reason it doesn't build is because the `Conversions` type is in the `Microsoft.VisualBasic` assembly, which you'll need to add a reference to.

For this reason I'm not going to change the default behaviour, but there are still a number of things that could be done to improve this experience in the web converter:
* List required assembly references and imports
* Add an option to prefer idiomatic C# over an exact conversion. For converting a whole project with the extension it makes sense to not want to track down a million minor differences, but in the web converter I think people sometimes just want something roughly similar.
* Add a special case for using these special VB methods on compile time constants which avoids using the VB method in cases where it makes no difference (such as this one). In this case it could be simplified to just `','` in the extreme

**Comment by GrahamTheCoder** [comment]
#174 covers some related cases
