### ISSUE TITLE
FR: VB -> C#: Obey editor config when formatting output

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#448]
**Is your feature request related to a problem? Please describe.**
I wanted my output code to be clean. We migrate a lots of code and now we need to manually add curly braces...

**Input code**
```vbnet
If Something Then
  myVar = True
Else
  myVar = False
End If
```

**Erroneous output**
```C#
{
    if (Something)
        myVar = true;
    else
        myVar = false;
}
```

**Describe the solution you'd like**
```C#
{
    if (Something)
    {
        myVar = true;
    }
    else
    {
        myVar = false;
    }
}
```

**Describe alternatives you've considered**
A checkbox in https://codeconverter.icsharpcode.net/ to turn on/off this feature

**Comment by mrmonday** [comment]
If you're using Visual Studio, you can use the `csharp_prefer_braces` editorconfig setting (https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019) and then format the file, to save manually doing it (and also to automatically enforce it across your entire project).

I think a bigger stylistic issue with produced code is that you can end up with pirate braces
```c#
if (x)
    y();
else 
{
    z();
    a();
}
```
```c#
if (x)
{
    y();
    z();
}
else
    a();
```

**Comment by GrahamTheCoder** [comment]
Consolidating test case: #447

**Comment by GrahamTheCoder** [comment]
I've changed this to cover the more general issue so that we don't end up reimplementing every possible formatting setting. There's a small chance that it even already works if you have the editor config set up for c# in your solution at time of conversion, but if not, we can probably make it work by loading an option set from editor config and passing it to the simplifier. That plus a little documentation should cover all stylistic requests. I do agree that the "pirate braces" (never heard that name before) exhibit a style that is particularly odd, so I'd happily accept a PR to avoid that particular case (unless it takes 100s of lines of code in which case it might be easier to set a default option set and apply it).

**Comment by GrahamTheCoder** [comment]
I looked into this, since there's a nicely packaged tool intended for exactly this I'm going to put it out of scope. I've added a note to the wiki that I recommend people use:
https://github.com/dotnet/format
