### ISSUE TITLE
VB -> C#: Runtime error for incorrect arg type converted to compile time error

### ISSUE THREAD

**Issue by pmantos** [icsharpcode/CodeConverter#476]
### Input code
        Catch ex As Exception
            MsgBox(ex.ToString, "PostWaterFallData_ThreadSafe", True)

### Erroneous output
            catch (Exception ex)
            {
                Interaction.MsgBox(ex.ToString(), (MsgBoxStyle)"PostWaterFallData_ThreadSafe", true);
            }

### Expected output
                Interaction.MsgBox(ex.ToString(), (MsgBoxStyle) MsgBoxStyle.Information , "PostWaterFallData_ThreadSafe");

Note: Am unsure what the TRUE means in the original VB.Net MSGBOX. The informational style is just a guess

**Comment by GrahamTheCoder** [comment]
Sorry if I've missed something here, but as I can see, the input code you've given would always have thrown an error at runtime. 

The method signature of MsgBox is:
```csharp
public static MsgBoxResult MsgBox(object Prompt, MsgBoxStyle Buttons = MsgBoxStyle.OkOnly, object Title = null)
```

Since the original code threw an error at runtime, a more faithful conversion would be to trick the compiler with an extra cast:
```csharp
Interaction.MsgBox(ex.ToString(), (MsgBoxStyle)(object)"PostWaterFallData_ThreadSafe", true);
```

The output you suggested is a reasonable guess at what was originally intended, but since the original code threw an error, it's not really a faithful conversion, and there's no generally applicable rule that would get this result so I can't make the converter generate that.

One of the differences in C# is that you get more of these errors at compile time. This is great for writing a robust app, but some people find it annoying when they just want to sketch out a quick prototype. I'll leave this issue open for now to track this mismatch. I'm hesitant to do work which helps hide bugs in people's code but we could do something to make it more obvious what's happened here potentially. Thanks for the bug report!

**Comment by GrahamTheCoder** [comment]
I've now found very similar case where [previously working code](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUAAoCuEwAlgMaEDCwAhviLd6hUYWatOJABZ9slGCRaEAsnzYA7ABQBKEWIMARNqkKUAHoQCCRYrmyaA5voOiV+RwCFM5rRaiEAEQAjIEBACrYTJR6dAYAohqKxCwuohLsXMSy8snK7l4+Wp6kAGp8wOLYmBi41kQA8hAAVpQcuAEl5ZUN6LhsmBoVhJ5MuLiDRDaqHt7mdqTAlIQAvDOF87iLlAB0DQDWDRrApJ1lw739g8PhbLhL9YRNre2rhABymLjSTjqEaYREnkIPQgTx+IJ6PQMlJEkxTAU5gslmkDkcTqCkoCNPCgA=) will fail to compile

With that it's now easier to see the correct fix here, which is to convert to the relevant numeric type, then cast to integer.
