### ISSUE TITLE
C# -> VB: Variable Declaration with Nullable Default Expression

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#486]
### Input code
```csharp
var vbInitializerTypeInfo = vbInitValue != null ? _semanticModel.GetTypeInfo(vbInitValue) : default(TypeInfo?);
```

### Erroneous output
```vbnet
Dim vbInitializerTypeInfo = If(vbInitValue IsNot Nothing, _semanticModel.GetTypeInfo(vbInitValue), Nothing)
```

### Expected output
```vbnet
Dim vbInitializerTypeInfo? = If(vbInitValue IsNot Nothing, _semanticModel.GetTypeInfo(vbInitValue), Nothing)
```

### Details
A CS variable declaration with a conditional expression containing a nullable default expression does not convert to a nullable variable.

Meaning: "Dim vbInitializerTypeInfo" should be "Dim vbInitializerTypeInfo?"

* Version in use: Current compiled repo

**Comment by GrahamTheCoder** [comment]
Thanks for the report. I've done some cursory testing on this case. It turns out the "?" on the outer variable didn't get the right runtime result because the issue was the loss of type information between default(TypeInfo?) and Nothing.
Here's my [minimal example](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoB0ASpQGbCUDGuAlpgHYCwAUAIAKAVwjAOrQgGFgAQ3xEA6gAtSSygDlKlGABVM0hbk2ZcKjtwDmAwncKjxkkmMIBRAB5yMLABSRkbg5cADU5YBFKAH5CAEEiQKorSmwASlt7TIARDlRCAHdglSMKQgBeQmRGfwhA4LCIykr8U1xCVotrKEIAdm6c7DZcEtxfDssrbsTKZOwo1PT+TOX7HLzuQ2NyyuqAoNDwyObW9rNOyd7u8etFzLduGBcIAXvH2QV8IA==) demonstrating my suggested fix:
```vbnet
    Public Sub Example(vbInitValue? As Integer)
        Dim noCast = If(vbInitValue IsNot Nothing, 7, Nothing) ' The Nothing resolves to default(int), which is 0
        Dim withCast = If(vbInitValue IsNot Nothing, 7, DirectCast(Nothing, Integer?))  ' The Nothing resolves to default(int?), which is null
    End Sub
```
