### ISSUE TITLE
VB -> C#: Resources Text can not be called if not the default one

### ISSUE THREAD

**Issue by marcal** [icsharpcode/CodeConverter#551]
Hello,

I have created a sample project where I have added a new resource text (Lng) instead of using the default one. 
[TestRes.zip](https://github.com/icsharpcode/CodeConverter/files/4368065/TestRes.zip)
The project compiles correctly but I can't access the resources from the resx file after a conversion to C# (can't find the resource for the specified culture).

EDIT : I believe I didn't understand your other comment before because simply changing the modifier from internal to public (compiling) and after that to internal again solves the problem so I guess there were two problems (one that I reported and one that you saw).

EDIT2: On another project, changing the modifier doesn't work. I have to remove the field Custom Tool Namespace (in the designer) and press enter and put back the value in it).

Thank you again
Marc

**Comment by GrahamTheCoder** [comment]
Thanks. For the previous issue, I had assumed that the My Project folder was special. It turns out that Visual Basic compiles all resources to be in the root assembly namespace rather than the folder they're in (like C# does). So I probably just need to remove this if statement, thus moving all resource files to the project root:
https://github.com/icsharpcode/CodeConverter/blob/e87fef11338b8d136b9f0e2d97fa3e7f6b7d86a6/CodeConverter/CSharp/DesignerWithResx.cs#L25

I'll try it out sometime soon

**Comment by marcal** [comment]
Hello,

It is correct, you can create a resource in the Res directory, or in another directory and you will be able to access them without specifying the directory they were in.

**Comment by GrahamTheCoder** [comment]
I also verified that it's a VB compiler error to create two resource files with the same name in the same project.

**Comment by Saibamen** [comment]
Please retest with recent version

**Comment by marcal** [comment]
Hello,
It is still working fine with 8.0.4.0

Thank you
