### ISSUE TITLE
Null reference Exception generated during converion (VS 2019) Extension v8.0.4.0

### ISSUE THREAD

**Issue by dTrimon** [icsharpcode/CodeConverter#560]
### Steps to reproduce
1. allmost all files in my project generate this error. Not sur how to reproduce without sending you my code

### Error message shown
[url=https://zupimages.net/viewer.php?id=20/15/e1z9.png]
### Details
* Product in use: VS extension  v8.0.4.0

* Did you see it working in a previous version, which: This is my first try

**Comment by GrahamTheCoder** [comment]
Hi there. Thanks for posting. From the stack trace it's likely to be a delegate declaration in a winforms project that ends up converted with a missing type. I'll try to recreate the issue locally, but if you could isolate the snippet of code that causes the issue and send me that it'd help. Note: Because this is a project level error, it may occur for any files in the same project as the problematic one. But if you don't have many delegates hopefully it'll be easyish to track down. Thanks!

**Comment by GrahamTheCoder** [comment]
I have managed to find a repro (it's quite simple actually!)
```vbnet
Delegate Sub DelegateType(x)
```
So if any of your delegates are missing a type on their parameter, you may be able to workaround the issue by adding "As Object" or something similar like:
```vbnet
Delegate Sub DelegateType(x As Object)
```

I'll try to get a fix for this released in the next week or so since it's a total show stopper.
