### ISSUE TITLE
VB -> C#: DataGridViewTextBoxColumn ambiguous naming error

### ISSUE THREAD

**Issue by maffh92** [icsharpcode/CodeConverter#569]
Visual studio renames columns(DataGridViewTextBoxColumn) of a DataGridView automatically when redesigning a windows form. This produces an ambigiuous naming error.

### Reproduce steps 

1. Make a new windows form project(visual basic)
2. Add DataGridView to the Form1.vb
3. Add column(e.g Columns1) to DataGridViewTextBoxColumn 
4. Convert vb.net project to c#
5. Open c# project
6. Open Form1.cs
7. Move 1 form element(To regenerate the designer file)

The last step changes the name of the DataGridViewTextBoxColumn to the same name as the property. 

### Details
* Product in use:  both
* Version in use: all(master branch) - dbe18edd80339a366ca04fcff2808432f7353881
* Did you see it working in a previous version, which? No
* .net version(converted project): .net framework 4.7

**Comment by GrahamTheCoder** [comment]
Thanks for the comprehensive bug report. I'll try to repro/investigate it at least this weekend.

**Comment by GrahamTheCoder** [comment]
I've reproduced the issue with the steps you posted 👍 

A workaround is to put an underscore on the control name in the designer.cs file.
e.g `this._Col1.Name = "_Col1";`
If you need the name to be what it originally was, you can set it back in the constructor straight after initializecomponent.

I think I'll implement this as the solution in the converter since I think it's the closest I can get the code to be

**Comment by GrahamTheCoder** [comment]
This is now fixed in master in the way described above and should be released in the next week.
Feel free to build from source or use a CI build as explained on the [readme](https://github.com/icsharpcode/CodeConverter#other-ways-to-use-the-converter) if you want to try it out before then.

**Comment by maffh92** [comment]
Thank you for solving the problem! It works. Do you know why the converter adds an additional property for a DataGridViewTextBoxColumn? Like:
`        private DataGridViewTextBoxColumn _Column2;

        internal DataGridViewTextBoxColumn Column2
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Column2;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set

                _Column2 = value;
            }
        }

The designer doesn't add this additional property when an user adds a DataGridViewTextBoxColumn to the form.

**Comment by GrahamTheCoder** [comment]
You're welcome, thanks for confirming it works for you! 😃 
If you look in the Designer.vb file (hidden by default), you'll see that the Column2 field has a "WithEvents" modifier. That causes the VB compiler to treat it as a property so that handlers can be updated if the field is reassigned.
The converter does the same in order to maintain the same behaviour at runtime, which is what you've noticed here. However, in cases where no events are actually handled (like this one), the property is redundant which clearly makes it hard to understand why it's there (and generally a waste of space).
I've opened a feature request #572 to optimize away the property in this case in order to create shorter and more idiomatic C#, give it a thumbs up if you think it's the right idea, or add any other comments as appropriate. Thanks!
