### ISSUE TITLE
Nothing appears in output window when trying to convert C# to VB.NET from within VS2017C

### ISSUE THREAD

**Issue by PWolly** [icsharpcode/CodeConverter#577]
Most likely not a bug - I probably caused this by inadvertently installing the NuGet package rather than as an extension. Once I realized this, I removed all the NuGet packages and installed as an extension and when I try to convert a snippet, .cs file or c# project I see nothing in the VS output window. Any advice on how I might be able to fix without resorting to uninstalling+reinstalling VS would be greatly appreciated.

**Comment by GrahamTheCoder** [comment]
Hi, interesting case. Do you know what version of 2017 you have? Could you paste the info from the about box? If it's before 15.7, you'll need to use a later visual studio or earlier code converter the earliest version I'm testing on is 15.9
From what you've said I'm assuming you saw the conversion menu item, clicked it, then nothing happened, is that right?

**Comment by PWolly** [comment]
Hello,
The VS2017C version on machine that CodeConverter was “silently failing” on was 15.7-something, I have updated it to 15.9.23 and it now works. Yesterday, after reaching out for advice, I installed the extension on a second PC in VS2017C V15.9.21 and it worked fine.
To answer your last question, yes, I was initiating the conversion via the right mouse menu “Convert to ..”. Its’ absence was my first clue to read your directions which clearly states to install as an extension – lesson learned.
Curious to know why, when I manage NuGet packages and search for CodeConverter, these two show up, and what the use case(s) would be?
[cid:image003.jpg@01D63B23.6C342860]
Thanks for the quick reply,
Best regards

**Comment by GrahamTheCoder** [comment]
Glad it's now working. Sorry for the inconvenience - the features the converter uses weren't available a few years ago when that version of Visual Studio was released.

I can't see your image, but I imagine it showed:
* https://www.nuget.org/packages/ICSharpCode.CodeConverter/
  * A normal nuget package. You install it in a project, then you can call it from your code.
  * Useful if building a tool which converts code, or if you want finer-grained control over what's converted.
* https://www.nuget.org/packages/ICSharpCode.CodeConverter.CodeConv/
  * This is a special type of package containing a dot net tool, you shouldn't install within a project.
  * If you view the link above it advises to install like this:
`dotnet tool install --global ICSharpCode.CodeConverter.CodeConv --version 8.1.3`
Once you've done that you can then use the command line like: `dotnet codeconv c:\path\to\your.sln` rather than converting from within visual studio.

I'll update the package descriptions to try to give more information

**Comment by PWolly** [comment]
Hello GrahamTheCoder,
Once again thanks for the quick reply. Sorry something stripped out the embedded image but turns out it didn’t matter as you imagined correctly. Appreciate the explanations and your great extension!
Best regards
