### ISSUE TITLE
VB -> C#: conversion of individual file runs well but same file on project conversion produced bad C# code

### ISSUE THREAD

**Issue by desbaratizador** [icsharpcode/CodeConverter#595]
### Input code
```vbnet
RuleFor(Function(x) x.Expedidor).Length(0, LEN_EXPEDIDOR)
RuleFor(Function(x) x.ExpedidorNome).NotEmpty.Length(1, LEN_EXPEDIDOR_NOME)
RuleFor(Function(x) x.ExpedidorMorada).NotEmpty.Length(1, LEN_EXPEDIDOR_MORADA)
RuleFor(Function(x) x.ExpedidorLocalidade).NotEmpty.Length(1, LEN_EXPEDIDOR_LOCALIDADE)
```
### Erroneous output
```C#
RuleFor[x => x.Expedidor].Length(0, LEN_EXPEDIDOR);
RuleFor[x => x.ExpedidorNome].NotEmpty.Length(1, LEN_EXPEDIDOR_NOME);
RuleFor[x => x.ExpedidorMorada].NotEmpty.Length(1, LEN_EXPEDIDOR_MORADA);
RuleFor[x => x.ExpedidorLocalidade].NotEmpty.Length(1, LEN_EXPEDIDOR_LOCALIDADE);### Expected output
```
```C#
RuleFor(x => x.Expedidor).Length(0, LEN_EXPEDIDOR);
RuleFor(x => x.ExpedidorNome).NotEmpty().Length(1, LEN_EXPEDIDOR_NOME);
RuleFor(x => x.ExpedidorMorada).NotEmpty().Length(1, LEN_EXPEDIDOR_MORADA);
RuleFor(x => x.ExpedidorLocalidade).NotEmpty().Length(1, LEN_EXPEDIDOR_LOCALIDADE);
```
### Details
VS extension (web converter produces the error also)
version 8.1.5.0

**Comment by GrahamTheCoder** [comment]
Thanks for the report. Could you share the defininition of RuleFor?
If it's an indexer then that output would be correct, but presumably it's a method?

The converter is acting as if it can't find the definition. Though I think that guessing behaviour could be improved too, so that it depends on the arg type - only guessing indexer when it's an int argument (I.e. Array access)

**Comment by desbaratizador** [comment]
RuleFor is a method from FluentValidation: [https://docs.fluentvalidation.net/en/latest/start.html](url)

I think you are right, "The converter is acting as if it can't find the definition" , the definition exists in the project as a reference, but in the conversion somehow...

Thanks.

**Comment by GrahamTheCoder** [comment]
I have created a project file from the code you wrote, but it converts correctly for me in VS 16.7.0 Preview 3.1
Could you check if this cut down project works for you?
If it works fine, could you try to figure out what needs adding from your full project in order to break it?
If it doesn't work, could you give me details of your visual studio verison?
[Issue595ReproAttempt.zip](https://github.com/icsharpcode/CodeConverter/files/4943672/Issue595ReproAttempt.zip)

Thanks for your help

**Comment by desbaratizador** [comment]
Last time i used the converter, a really good tool, this issue disappeared, so i will close him.

P.S.: issue #592 remains (at same conversion of above), but i will need to convert more projects, wait for the feedback


Thanks

**Comment by GrahamTheCoder** [comment]
I believe this is also related to dotnet/roslyn#6615
