### ISSUE TITLE
C# -> VB: Hundreds of errors and warnings after converting.

### ISSUE THREAD

**Issue by DotNetTester** [icsharpcode/CodeConverter#603]
I tried converting a old open source project on google code to VB .NET and the result was hundreds of errors (a little over four hundred to be exact) in Visual Studio. I suspect after looking through the code that a large part of problem is that the converter isn't handling the WinForms Designer code properly. I believe I read somewhere that it's handled a little differently in VB .NET vs C#. In VB .NET, it's hidden from the user vs. in C# where it's not, I think. Would it be alright if attached the project or provided a link to it?

I used the newest version of the converter with Visual Studio 2017.

**Comment by GrahamTheCoder** [comment]
Thanks for the message, I'll consolidate this into #170 since it has more information surrounding information on known issues.
The most valuable detail to add there would be any specific issues (especially a common pattern) you see. A link to a repository is also welcome. If you're interested in working on a PR for any of the issues let me know and I'll be happy to help find a good starting point.
