### ISSUE TITLE
VB -> C#: Null coalesce missing brackets

### ISSUE THREAD

**Issue by jmeijrink** [icsharpcode/CodeConverter#626]
### Input code
```vbnet
Public Class VisualBasicClass
   Public Sub New()
       Dim y As String = If(("xxx")?.InnerText, String.Empty).ToUpper()
   End Sub
End Class
```

### Erroneous output
```C#
using System;

public partial class VisualBasicClass
{
    public VisualBasicClass()
    {
        string y = "xxx"?.InnerText ?? string.Empty.ToUpper();
    }
}
```

### Expected output
```C#
using System;

public partial class VisualBasicClass
{
    public VisualBasicClass()
    {
        string y = ("xxx"?.InnerText ?? string.Empty).ToUpper();
    }
}
```

### Details
* Because the parentheses are missing in the Erroneous output the value of .InnerText is not uppercased. But left in lowercase.
* Current online code converter at https://codeconverter.icsharpcode.net/ can be used to reproduce this issue.

**Comment by GrahamTheCoder** [comment]
Should be a very straightforward fix. Let me know if you're interested in having a go and want some hints.

**Comment by SuperRembo** [comment]
Actually for the ternary operator parenthesis are added when needed, but not for the null-coalescing operator.

I've added [a test](https://github.com/SuperRembo/CodeConverter/blob/a82e43188bb8e487db1b85ce2be8023a15dd93be/Tests/CSharp/ExpressionTests/ExpressionTests.cs#L1658) to describe the issue, but don't have a clue how to fix it. It would be nice to get some hints.

**Comment by GrahamTheCoder** [comment]
Nice, always good to start with the test. OK, so the first thing is to figure out which syntax type the expression is. [SharpLab](https://sharplab.io/#v2:DYLgbgRgNALiCGBnGUAmIDUAfACgVwmAEsBjAAgGFglEyA1IxPeYAISVKpoFgAoMgfkKkyAZQJkAcgFMA7gAoAlHwGqBAESIBbMgE8yAQVqiYAJyIA7AOZkAvGQCSAM3nyARAA8vbxVDFnLKwA6AFEtAAcYXUUggBUAewBVcPDpUyUVARCLVDECPmzcrkREIA===) has a nice syntax tree viewer:

![image](https://user-images.githubusercontent.com/2490482/93013803-a5e5da00-f5a3-11ea-99a4-f3f7e1903c7c.png)

Then you'll usually find there's a "Visit" method for that syntax construct (in this case within the CSharp namespace since that's the target language)

https://github.com/icsharpcode/CodeConverter/blob/1bb96eed1f2064e4ebfa857dfcd2b3dbed0fa571/CodeConverter/CSharp/ExpressionNodeVisitor.cs#L612-L619

So if you breakpoint that, your test should hit it

You may notice that right below that method is the ternary case which you mentioned works, so see if you can make this one work using a similar mechanism.

**Comment by SuperRembo** [comment]
I applied the same mechanism as used for the ternary operator. That makes the test pass.

I'm not sure what the purpose of `node.Parent.IsKind(VBasic.SyntaxKind.Interpolation)` is. It seems to be intended for when the operator is used in string interpolation, but the tests pass without this check.

**Comment by SuperRembo** [comment]
In other words: would `node.ParenthesizeIfPrecedenceCouldChange(expr)` be sufficient?

**Comment by GrahamTheCoder** [comment]
Yeah sounds right. I think it's a special case: within string interpolation, ternary statements need parentheses in c# to avoid a compile error. Should have really had a comment.

Could write a test to check this works within string interpolation to be sure.

**Comment by GrahamTheCoder** [comment]
Ah yes, just saw you did a test for it, nice
