### ISSUE TITLE
If statement not converting properly when "Nothing" is used.

### ISSUE THREAD

**Issue by ggoodnig** [icsharpcode/CodeConverter#630]
We had some "if" statements in our VB code which looked like this.

**If Not i Is Nothing Then
--do something
End If**

It converted as

**if ( i is object)
{
  //do something
}**

I believe it should convert to checking for not null.
**if (i != null)
{
  //do something
}**

**Comment by GrahamTheCoder** [comment]
Sorry for any confusion. I appreciate this type of null check isn't very commonplace yet. I use it because it neatly avoids any questions about whether the "!=" operator is overloaded. At some point I intend to update it to the even newer, shorter and more extensible:
```csharp
if ( i is {})
{
//do something
}
```

This means the same for reference types, but naturally extends to allow other pattern checks such as:
```csharp
if ( i is {SomeProperty: {}, ObjType: 7})
{
//do something
}
```
I'm just waiting until enough people move off old Visual Studio versions from 2017 which didn't support it.

**Comment by ggoodnig** [comment]
@GrahamTheCoder Appreciate your comment.  I closed it after I thought about it more and realized it is actually accomplishing the same thing, even though it was different than what I expected.
