### ISSUE TITLE
VB -> C#: Duplicated literal type specifier

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#633]
### Input code
```vbnet
Debug.Print(DoubleFunction(3D).ToString)
Debug.Print(DoubleFunction(CDec(0.3)).ToString)
Private Shared Function DoubleFunction(value As Double) As Double
    Return value
End Function
```

### Erroneous output
```C#
Debug.Print(DoubleFunction(3Dd).ToString());
Debug.Print(DoubleFunction((double)0.3d).ToString());
```

### Expected output
```C#
Debug.Print(DoubleFunction((double)3m).ToString());
Debug.Print(DoubleFunction((double)0.3m).ToString());
```

### Details
* Product in use: VS extension
* Version in use: 8.1.8.0
* Did you see it working in a previous version, which? No

**Comment by GrahamTheCoder** [comment]
Ah, that took me a moment to spot. I see it's duplicated the "D" incorrectly.

With that removed it behaves the same from what I can see:
* [Running VB](https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACgAFRCYASwGNKAYWABDclSHtKMylx4CaAC1HxGaGt0oBZUb2QAKAJTTZZocWTliwRgDoA6vF5MAMvsYGAIsW62AYij8MLyWBgDMXkZ2ACrE1DDOyADmJmxm5pbWto7Obh7evjyMgcjBoYZCXoz8BgAMduFG0XEJSammMgCiyBrU3OwczmCiTMqq6pSl5ZaUPn4lQSFhI8CIjJQAglTzxUZbO0W2nZQASowwiPDIlKvr7D0a08vID73CYhJAA=)
* [Running converted to C# with extra d removed](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLACgACAmAjBjTAZgAIAHAQzGAEsKAbEnEgYQwG8MTuntsuendDxFNcATgAUAEQD2EAEb0AppgCstWVElFpASgB0AFVkBlYGBpQA5pL16A3ANFipcxSvWbtABgNE4QxNzSxs7R2cSAF8CYR4ySwA3CmBlMQA2Ejh5JTT3XK8aLUlsjzTk+ghlPUihF25MAHYSCqqnOO4Y9CigA)

Just to explaing what's going on here a bit more, the `CDec(0.3)` in your input has been turned into "0.3m".
The cast to double is silently added by the VB compiler since the method being called requires a double, and hence is added explicitly in the C# conversion.
