### ISSUE TITLE
VB -> C#: Parameterized Property optional parameter in wrong place and missing value

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#642]
### Input code
```vbnet
    Protected Property AttributeValue(<Runtime.CompilerServices.CallerMemberName()> Optional ByVal name As String = Nothing) As Double
        Get
…
        End Get
        Set(value As Double)
…
        End Set
    End Property
```

### Erroneous output
```C#
        protected double get_AttributeValue([System.Runtime.CompilerServices.CallerMemberName()] string name)
        {
….
        }

        protected void set_AttributeValue([System.Runtime.CompilerServices.CallerMemberName()] string name, double value)
        {
…
        }
```

### Expected output
```C#
        protected double AttributeValueGetter([System.Runtime.CompilerServices.CallerMemberName()] string name = "")
        {
…
        }

        protected void AttributeValueSetter(double value, [System.Runtime.CompilerServices.CallerMemberName()] string name = "")
        {
….
        }
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* Version in use: 8.1.8
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. N/A

**Comment by GrahamTheCoder** [comment]
Hi, thanks for posting. I completely agree this would be a more idiomatic C# name. However, the current name is intentionally set to maximise the chance of source code compatibility for any referencing projects that are already in C# (since it's the name the vb compiler picked), so I'm very reluctant to change it and for that reason I'm going to close the issue. If I'm wrong about the compatibility, or there are other good reasons to do this that I haven't mentioned, please feel free to add more information and reopen

**Comment by AteCoder** [comment]
the name issue is totally secondary.  Of issue is the broken C# code.  It will not work for two reasons:
1: the optional argument must be last; 
2; the optiional value must have a default value, nothing in this case.

**Comment by GrahamTheCoder** [comment]
Thanks, that makes sense, sorry I missed it!

**Comment by GrahamTheCoder** [comment]
```csharp
.method family specialname 
        instance void set_AttributeValue (
            [opt] string name,
            float64 'value'
        ) cil managed
```

I've checked the method signature in IL. Unfortunately IL supports optional parameters preceding non-optional ones (since the values are compiled into the caller). So if I flip the order, then any existing assemblies compiled against this getter/setter will be broken. But even worse, if they're the same type, any referencing code will keep compiling but have a different meaning.
That's just the kind of incredibly subtle logic bug that I hate to track down, so I'm inclined to actually make the "value" parameter optional in this edge case, and keep the order the same, i.e.

```csharp
        protected double get_AttributeValue([System.Runtime.CompilerServices.CallerMemberName()] string name = null)
        {

        }

        protected void set_AttributeValue([System.Runtime.CompilerServices.CallerMemberName()] string name = null, double value = default)
        {

        }
```

**Comment by GrahamTheCoder** [comment]
Ah, I made this change but haven't really thought about what happens at the callsite. From the existing test, I'm wondering whether I'd intended to inline the default value at the caller. But obviously this case you've given makes that a bit more awkward. What a messy situation 🤔

**Comment by GrahamTheCoder** [comment]
I've checked this and it looks like it'd work:

```vbnet
Imports System
Imports System.Linq

Public Class Class717
    Sub Main()
        AttributeValue = 3
    End Sub
            
   Protected Property AttributeValue(<Runtime.CompilerServices.CallerMemberName()> Optional ByVal name As String = Nothing) As Double
        Get
                    Return Nothing
        End Get
        Set(value As Double)

        End Set
    End Property
End Class
```

goes to

```csharp
using System.Runtime.CompilerServices;

public partial class Class717
{
    public void Main()
    {
        set_AttributeValue(null, 3d);
    }

    protected double get_AttributeValue([CallerMemberName()] string name = null)
    {
        return default;
    }

    protected void set_AttributeValue([CallerMemberName()] string name = null, double value = default)
    {
    }
}
```

So I'll close this issue as fixed
