### ISSUE TITLE
VB -> C#: Enum converted to values

### ISSUE THREAD

**Issue by AteCoder** [icsharpcode/CodeConverter#675]
### Input code
```vbnet
Public Enum UserInterface

    ''' <summary> An enum constant representing the unknown option. </summary>
    <System.ComponentModel.Description("Unknown")> Unknown

    ''' <summary> An enum constant representing the spectrum option. </summary>
    <System.ComponentModel.Description("Spectrum")> Spectrum

    ''' <summary> An enum constant representing the spectrum Milliseconds option. </summary>
    <System.ComponentModel.Description("Spectrum Chart")> SpectrumMs

    ''' <summary> An enum constant representing the wisdom option. </summary>
    <System.ComponentModel.Description("Wisdom")> Wisdom

    ''' <summary> An enum constant representing the wisdom Milliseconds option. </summary>
    <System.ComponentModel.Description("Wisdom Chart")> WisdomMs
End Enum

    Protected Overrides Sub OnLoad(e As EventArgs)
        Dim activity As String = String.Empty
        Try
            activity = $"{Me.Name} adding spectrum view"
            Select Case CommandLineInfo.UserInterface
                Case UserInterface.Spectrum
                    Me.ModelViewBase = New SpectrumView
                Case UserInterface.Wisdom
                    Me.ModelViewBase = New WisdomSpectrumView
                Case Else
                    Me.ModelViewBase = New SpectrumView
            End Select
            Me.AddTalkerControl($"{CommandLineInfo.UserInterface}", Me.ModelViewBase, False, False)
            ' any form messages will be logged.
            activity = $"{Me.Name}; adding log listener"
            Me.AddListener(My.Application.Logger)
        Catch ex As Exception
            Me.PublishException(activity, ex)
        Finally
            MyBase.OnLoad(e)
        End Try
    End Sub
```

### Erroneous output
```C#

                switch (CommandLineInfo.UserInterface)
                {
                    case 1:
                        {
                            ModelViewBase = new SpectrumView();
                            break;
                        }

                    case 3:
                        {
                            ModelViewBase = new WisdomSpectrumView();
                            break;
                        }

                    default:
                        {
                            ModelViewBase = new SpectrumView();
                            break;
                        }
                }

```

### Expected output
```C#
                switch (CommandLineInfo.UserInterface)
                {
                    case UserInterface.Spectrum:
                        {
                            ModelViewBase = new SpectrumView();
                            break;
                        }

                    case UserInterface.Wisdom:
                        {
                            ModelViewBase = new WisdomSpectrumView();
                            break;
                        }

                    default:
                        {
                            ModelViewBase = new SpectrumView();
                            break;
                        }
                }
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net) / VS extension 
* Version in use: 8.1.8.0 artifact of 10/12
* Did you see it working in a previous version, which? N/A
* Any other relevant information to the issue, or your interest in contributing a fix. 
This is the first time I am seeing this behavior.

**Comment by marcal** [comment]
Hello,

Out of curiosity, can you please tell me why it is wrong?
I have tons of Enum in a project with select case and it would be really bad for me to have integers instead of enum (I prefer to have an enum than an integer for the visibility?

**Comment by AteCoder** [comment]
Oops.  Please check the corrected report.  The converter changes the Enum Names to Enum values.

**Comment by GrahamTheCoder** [comment]
Thanks, I can imagine this might happen when the type of the expression being switched on is int rather than enum. Might be more general than that though.

**Comment by AteCoder** [comment]
The type was: UserInterface? 

Nullable Enum

**Comment by GrahamTheCoder** [comment]
Ah yes, that'd do it. The expected output looks correct for that case.
[Isolated VB example in sharplab](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUPQAoCuEwAlgMaEDCwAhviIBRAHbNUAFUoV6heYRZsuhMRMIBVfJWzJRVbADN+nSnIUWNogNajMAd1HmL84ukqdc2Cc5cB1dnwYTFo6CzEYVXFQ3yUObmJWQgB5UQAZTH4YAApmdkIAQSItHT0DY1MAfgBKXwsAEXZUQhNcdjB2XFJCAF5CAAY6l1dKYA9cXkFKQjyh4YseKZn85CIAOUxcAAt2UQBzOfnh1vbO7r6ARkOjxe1NbV19HQrKADo3ce9Qo5+FE46ur1CAAma7zW7TEqPcomN4BIIhMG/f5nIEAZiRLghqmA2kxRxRgL6ABZMRESKNxr5yYkIPRyXxBPggA=)
[Expected C#](https://sharplab.io/#v2:CYLg1APgsAUAAgZgAQAcCGAnALgSzQGyTgCYkBRAOwFcBbAFQFMBnLWAb1iS6OQepqQBVJgwwBJCllEAzNAGMGnbhxjc1QigGsKAewDuFADRL1SAMooGcrBlrHVppAHUcTYDpomkAX1hfERAAsSADyFAAyOmjAABTCohJSGLIKAPxIVDgAlF4qjkg4kkjyuABuOFgAnkgAvEgADADcXmpMehVyABZIMZk5DqZ5+dxyaCJIpZhEcKPjep18GTgFTEjU+PggLcNcQzv5JTjlVbVIAIzNA/umAEYYDGial9dqvjDbprMMQiLikjLyBgAOgsVhstC2V2uexeakOx2qdWIz1h6juDyeH2Gbyxai+XHifySKWBLjcHkhqKQMKp8IqiKQCBRVK46MezJeOKhjmADFkVHwWEpqJpqLpJzqgQ5VLZmO5Oze+UV3De3iAA)
In my example I've added the extra complication of checking for "Is Nothing" since that also causes broken output, but if that's non-trivial to fix I'll break it out into a separate issue.

**Comment by AteCoder** [comment]
I am curious to know if the Converter could then be programmed to create a Case structure like VB or  create a set of if's like sharplab?

On a side note, I have been chatting on this with my son in law who has been doing some AI language work.  Obviously, very different. Yet, the emergent richness of promamming languages is humbling as is language comprehension.

It seems like the team is enjoying the challenge. Great work!
________________________________

**Comment by GrahamTheCoder** [comment]
It'd definitely be possible to keep as case statements. SharpLab is calling through to ILSpy's decompilation, so it's building up minimal readable C# logic from the compiled IL rather than trying to mimic the original code style.

Yes it's a great testament to the human brain's ability to use abstraction that we are able to use natural and computer languages extensively without being able to define the details of how they work. Computers usually start from raw well-defined items and build up (e.g. programming language elements) but I saw some great examples of [GPT3](https://en.wikipedia.org/wiki/GPT-3) applying the more human-like top-down approach recently.
