### ISSUE TITLE
VB -> C#: Adding 'Financial' without reason

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#708]
### Input code
```vbnet
PV.MitEinfahrOeffnung = True
```

### Erroneous output
```C#
Financial.PV.MitEinfahrOeffnung = true;
```

### Expected output
```C#
PV.MitEinfahrOeffnung = true;
```

### Details
* Product in use: [codeconverter.icsharpcode.net](https://codeconverter.icsharpcode.net)
* Version in use: **New online tool doesn't show version number anymore**
* Did you see it working in a previous version, which? Don't know
* Any other relevant information to the issue, or your interest in contributing a fix.

**Comment by GrahamTheCoder** [comment]
Definitely an unfortunate and amusing result 😄 

By default, the snippet converter imports Microsoft.VisualBasic. Due to type promotion the compiler interprets PV as the method [`Microsoft.VisualBasic.Financial.PV()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.financial.pv?view=net-5.0) method.
Hopefully you can see what's happening by looking at the compile errors [here](https://sharplab.io/#v2:DYLgbgRgNALiCGBnGUAmIDUAfAkgWwAcB7AJxkQAIBZASwGMSjEiAzGAOgDUbEBXeYACEk9ALAAoCQAVeEYPQoBhYEkoBlXiUa8Adqho6A5stUSK5ijLkKNEChq1Fd+o1QCmMABZFUACgCUZhbBUpzstDAAogYs8J4kAPJuLCw6uoYUALwUACokvG5B5pF69rISJahKKoiIQA===)

With zero project context there will be millions of oddities like this, I can't see any simple general fix to improve this unfortunately. The workaround is to declare PV:
```vbnet
Dim PV
PV.MitEinfahrOeffnung = True
```

The only real solution is to convert more code at once, or use the VS extension which knows about project context. Sorry it's not better news!
