### ISSUE TITLE
C# -> VB: Should be Sub instead of Function

### ISSUE THREAD

**Issue by LarHel** [icsharpcode/CodeConverter#743]
### Input code
```csharp
list.ForEach(i => Console.Write("{0}\t", i));
```

### Erroneous output
```vbnet
list.ForEach(Function(i) Console.Write("{0}" & vbTab, i))
```

### Expected output
```vbnet
list.ForEach(Sub(i) Console.Write("{0}" & vbTab, i))
```

### Details
* Product in use: https://converter.telerik.com/

**Comment by GrahamTheCoder** [comment]
Thanks for the report. This is caused by the converter (and indeed the VS compiler it uses) not being able to guess the type of "list", "ForEach" and "Console". For fragments like this, I've added a handful of common using statements that will handle this case and some other similar situations.

Please note that converter.telerik.com is a very old version of this converter library so I'd recommend using the latest version of it at https://codeconverter.icsharpcode.net/ (though this bugfix hasn't been released there just yet either)
