### ISSUE TITLE
VB -> C#: Ref extension method not allowed in C#

### ISSUE THREAD

**Issue by docfresh** [icsharpcode/CodeConverter#785]
[This sample](https://stackoverflow.com/a/18267830/6079533) on StackOverflow does not convert 

The error is, "CS8337	The first parameter of a 'ref' extension method 'Add' must be a value type or a generic type constrained to struct."

### VB.Net input code
```vbnet
Imports System.Runtime.CompilerServices

Public Module MyExtensions
    <Extension()>
    Public Sub Add(Of T)(ByRef arr As T(), item As T)
        Array.Resize(arr, arr.Length + 1)
        arr(arr.Length - 1) = item
    End Sub
End Module

```

### Erroneous output
```C#
using System;

namespace FixityVB
{
    public static class MyExtensions
    {        
        public static void Add<T>(this ref T[] arr, T item)
        {
            Array.Resize(ref arr, arr.Length + 1);
            arr[arr.Length - 1] = item;
        }
    }
}
```

### Expected output
```C#
//unsure of correct output
```

### Details
CC 8.41

**Comment by docfresh** [comment]
This may work if you only limit the array to one type
`        public static void Add(this string[] arr, string item)
        {
            Array.Resize(ref arr, arr.Length + 1);
            arr[arr.Length - 1] = item;
        }`

**Comment by GrahamTheCoder** [comment]
I think it just needs `where T:struct` after the parentheses on the method definition. But we'll need to check the behaviour for classes too

**Comment by GrahamTheCoder** [comment]
On further reflection, in the example given, even if T is constrained to struct, it's invalid as an extension method in C# because the array isn't a value type, so you'd need to use the ref keyword at the callsite, but can't because the syntax for that doesn't exist.

In your specific case, the most idiomatic option is probably to define a method like this:
```csharp
        public static T[] Add<T>(this T[] arr, T item)
        {
            var newArr = arr;
            Array.Resize(ref newArr, arr.Length + 1);
            arr[arr.Length - 1] = item;
            return newArr;
        }
```
Then you would call it like: `myArray = myArray.Add(something)`. You have to be a bit careful of forgetting to assign it afterwards though, so I'd usually call with "WithAppended" or something like that to indicate it returns

In terms of what the converter can do, I think it's best that it just stops it being an extension method and updates any callers.
