### ISSUE TITLE
String concatenation turns out weird, uses objects instead of strings

### ISSUE THREAD

**Issue by docfresh** [icsharpcode/CodeConverter#799]
### VB.Net input code
```vbnet
    'get a URL for this issue to be loaded in a browser.
    Public Function GetLink() As String
        Dim strURL As String = FIXITY_APP_URL + "?cid=" + Me.iCityID.ToString + "&issue=" + Me.iIssueID.ToString
        Return strURL
    End Function
```

### Erroneous output
```C#
        // get a URL for this issue to be loaded in a browser.
        public string GetLink()
        {
            string strURL = Conversions.ToString(Operators.AddObject(Operators.AddObject(Operators.AddObject(Operators.AddObject(Master.FIXITY_APP_URL, "?cid="), iCityID.ToString()), "&issue="), iIssueID.ToString()));
            return strURL;
        }
```

### Expected output
```C#
        // get a URL for this issue to be loaded in a browser.
        public string GetLink()
        {
            string strURL = Master.FIXITY_APP_URL + "?cid=" + iCityID.ToString() + "&issue=" + iIssueID.ToString();
            return strURL;
        }
```

**Comment by docfresh** [comment]
8.40 conversion.

The code is correct and functions, however, there are unnecessary calls to Operators.AddObject().

I suspect because Master.FIXITY_APP_URL is defined in VB without a strong type:

Public FIXITY_APP_URL = "https://fixity.io/"

Thus it's converted into an object.  However, it is clearly a string based on the quotation marks.

**Comment by GrahamTheCoder** [comment]
You're correct, if you don't give a field a type in VB, it gets declared as object. For some situations similar to this for internal/private members I seem to recall the converter does occasionally tweak things where it's convenient to do so.

However, I'm going to close this particular case as "won't fix", because:
* I agree it's clearly a string initially, but what if some other assembly changes it at runtime?
* If the converter changes the type of something public, that's an API breaking change which could have other ramifications
* There are freely available VB/C# diagnostics/fixers based on roslyn which can help improve code en masse either before or after conversion. It's easy for someone to write/use a Roslyn VB diagnostic to fix up all cases of this. Tangling that logic within the converter is unncessary, there's already enough actual conversion to work without generally trying to improve the code quality.

I would reconsider this if someone feels strongly about improving some specific related (non API breaking) cases and is happy to spend the time to implement it. If someone creates/finds a separate fixer for this VB issue (e.g. in https://github.com/code-cracker/code-cracker) I'd happily recommend it in the wiki so long as it's of reasonable quality.

**Comment by docfresh** [comment]
Based on what you wrote I think you're right; while this would be a "nice to have", you have to consider other implications. I should have run a code cleanup/fixer before conversion, the variables should have been strongly typed before converting.  Not sure if you have a "prepping to convert" section of the documentation, but perhaps a "checklist for best results" would be in order.
