### ISSUE TITLE
VB -> C#: Using static

### ISSUE THREAD

**Issue by PeterSwinkels** [icsharpcode/CodeConverter#847]
### VB.Net input code
Imports System.Math

### Erroneous output
using System.Math;

### Expected output
using static System.Math;

### Details

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using

**Comment by GrahamTheCoder** [comment]
Ah yes, hadn't realised VB's imports worked that way, thanks!

**Comment by GrahamTheCoder** [comment]
I've just checked this. Turns out it was fixed last August in https://github.com/icsharpcode/CodeConverter/pull/746
Combined with your other bug report, it sounds like you're running an old version of the converter (e.g. the one Telerik hosts)
If you're seeing this issue on the latest version, please provide a full sample. Here's a working one for example

```vbnet
Imports System.Math

Public Class VisualBasicClass

    Public Sub x()
        System.Console.WriteLine(Cos(2))
    End Sub
End Class
```

Correctly converts to:
```csharp
using static System.Math;

public partial class VisualBasicClass
{
    public void x()
    {
        System.Console.WriteLine(Cos(2d));
    }
}
```
