### ISSUE TITLE
Preserve blank lines during VB>C#

### ISSUE THREAD

**Issue by CardenInsurance** [icsharpcode/CodeConverter#879]
**Is your feature request related to a problem? Please describe.**
When I use this tool to convert VB.NET to C#, it does a great job except it removes almost all of my blank lines.  Having some whitespace between certain groups of code is important to help the developer to easily see logical separation points between lines of code.

Original code:
```
<Display(Name:="Reinsurance Year")> _
Public SelectedReinsuranceYear As Int16

<Display(Name:="Record Type")> _
Public SelectedRecordType As String

<Display(Name:="Release Date")> _
Public ReleaseDate As Nullable(Of Date)
```

gets converted to:
```
[Display(Name = "Reinsurance Year")]
public short SelectedReinsuranceYear;
[Display(Name = "Record Type")]
public string SelectedRecordType;
[Display(Name = "Release Date")]
public DateTime? ReleaseDate;
```

Another example:
```
Dim listOfThings As New List(Of String)

With listOfThings
    .Add("section 1 - line 1")
    .Add("section 1 - line 2")
    .Add("section 1 - line 3")

    .Add("section 2 - line 1")
    .Add("section 2 - line 2")
    .Add("section 2 - line 3")
End With
```
gets converted to:
```
List<string> listOfThings = new List<string>();
listOfThings.Add("section 1 - line 1")
listOfThings.Add("section 1 - line 2")
listOfThings.Add("section 1 - line 3")
listOfThings.Add("section 2 - line 1")
listOfThings.Add("section 2 - line 2")
listOfThings.Add("section 2 - line 3")
```
but it should keep those line breaks that I put there on purpose for readability:
```
List<string> listOfThings = new List<string>();

listOfThings.Add("section 1 - line 1")
listOfThings.Add("section 1 - line 2")
listOfThings.Add("section 1 - line 3")

listOfThings.Add("section 2 - line 1")
listOfThings.Add("section 2 - line 2")
listOfThings.Add("section 2 - line 3")
```

**Describe the solution you'd like**
Never remove blank lines while converting languages, even if there is more than one in a row.

**Describe alternatives you've considered**
You could make that behavior configurable so anyone who wants to have all their blank lines purged can enable that setting.

**Additional context**
Code Converter (VB - C#) version 8.5.00
Visual Studio 2022 version 17.1.4

**Comment by CardenInsurance** [comment]
The online version has the issue too:
![image](https://user-images.githubusercontent.com/87817212/163470494-be5878f0-2647-4756-9782-9d217836d73c.png)

**Comment by GrahamTheCoder** [comment]
Thanks for the suggestion.
There's a closely related one here: https://github.com/icsharpcode/CodeConverter/issues/358
Though I'll leave them as separate issues for now since I think they could be tackled quite separately:
This one can likely be implemented as an adjustment to the comment conversion code.

**Comment by GrahamTheCoder** [comment]
If anyone wants to play around with this, you can tweak:
https://github.com/icsharpcode/CodeConverter/blob/15ce37d35df7e9b0f1fc142caa90e87ac2190eb3/CodeConverter/Common/LineTriviaMapper.cs#L116
and /or
https://github.com/icsharpcode/CodeConverter/blob/15ce37d35df7e9b0f1fc142caa90e87ac2190eb3/CodeConverter/Common/LineTriviaMapper.cs#L138
and then auto-recharacterize the tests to see the changes

I noticed two main issues:
1. It'd probably look most natural to skip a trailing newline after "{" and a leading newline before "}" since they effectively act as one
2. There are some expressions which generate drastically different numbers of lines in the source/target (e.g. see the XmlExpressionTests for example) which mean it might be better to try to preserve the *ratio* of newlines per source line rather than the absolute count. Though arguably in some cases those expressions could be laid out more neatly over multiple lines
3. The auto-formatter runs before the LineTriviaMapper and may mess with some details of the source itself making it harder to choose where to put newlines. To get around this you'd likely need to add special cases in CommentConvertingVisitorWrapper (try to keep this stuff out of the main conversion visitor pattern, it already has enough complexity to deal with)
https://github.com/icsharpcode/CodeConverter/blob/15ce37d35df7e9b0f1fc142caa90e87ac2190eb3/CodeConverter/CSharp/CommentConvertingVisitorWrapper.cs#L61

**Comment by CardenInsurance** [comment]
Apologies for my ignorance about this codebase, but I wonder if this can be made as simple as "leave blank lines where we found them" so it converts lines of code 1-to-1 as much as possible.  I think that Linting tools can automatically adjust formatting styles after this tool finishes its conversion, but no tools can put blank lines back in logical places where a human would put them.

Example#1
```
If a = b Then
DoStuff()
End If
MoreStuff()
```
should convert to
```
if (a == b) {
DoStuff();
}
MoreStuff();
```
Example#2
```
If a = b Then

DoStuff()

End If

MoreStuff()
```
should convert to
```
if (a == b) {

DoStuff();

}

MoreStuff();
```

**Comment by GrahamTheCoder** [comment]
The code tweak I mentioned above will work fine for the example you gave. Sorry for any confusion. My points 2 and 3 are regarding whether and how to deal with more complex transformations, where the input is of a different type/shape to the output. For example:


### Example 1

```vbnet
Class A(Of T)
End Class
Class B
    Inherits A(Of String)
End Class
```

Should this turn the syntactically necessary newline in VB to a non-idiomatic CS declaration, i.e.:
```csharp
internal partial class A<T>
{
}
internal partial class B 
: A<string>
{
}
```

Personally I'm tempted to add this case as an exception to the rule.

### Example 2

Another case that needs closer attention to get a good result is:

Input:
```vbnet
        Dim htmlOutput =
          <html>
              <body>
                  <%= From book In catalog.<Catalog>.<Book>
                      Select <div>
                                 <h1><%= book.<Title>.Value %></h1>
                                 <h3><%= ""By "" & book.<Author>.Value %></h3>
                                 <h3><%= ""Price = "" & book.<Price>.Value %></h3>
                                 <h2>Description</h2>
                                 <%= TransformDescription(book.<Description>(0)) %>
                                 <hr/>
                             </div> %>
              </body>
          </html>
```

In my ideal world would probably be formatted like this - though this is more related to the within-expression preservation of whitespace mentioned it https://github.com/icsharpcode/CodeConverter/issues/358
```csharp
var htmlOutput = new XElement("html",
    new XElement("body",
        from book in catalog.Elements("Catalog").Elements("Book")
        select new XElement("div",
            new XElement("h1", book.Elements("Title").Value),
            new XElement("h3", "By " + book.Elements("Author").Value),
            new XElement("h3", "Price = " + book.Elements("Price").Value),
            new XElement("h2", "Description"), TransformDescription((string)book.Elements("Description").ElementAtOrDefault(0)),
            new XElement("hr")
        )
    )
);
```
