### ISSUE TITLE
VB -> C# : Extension Conversion Issue - unexpected "this"

### ISSUE THREAD

**Issue by RachelDavids** [icsharpcode/CodeConverter#88]
### Input code
```vbnet
Imports System.Runtime.CompilerServices
Public Module MyExtensions	
	<Extension>
	Public Sub DoNothing(self As ClassType)
        End Sub
	<Extension>
	Public Sub DoNothing(self As ClassType, redraw As Boolean)
        End Sub
	<Extension>
	Public Sub DoNothing2(self As ClassType, redraw As Boolean, ano As Object)
        End Sub
End Module
```

### Erroneous output
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualBasic;
using System.Runtime.CompilerServices;

public static class MyExtensions
{
    public static void DoNothing(this ClassType self)
    {
    }
    public static void DoNothing(this ClassType self, this bool redraw)
    {
    }
    public static void DoNothing2(this ClassType self, this bool redraw, this object ano)
    {
    }
}
```

### Expected output
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.VisualBasic;
using System.Runtime.CompilerServices;

public static class MyExtensions
{
    public static void DoNothing(this ClassType self)
    {
    }
    public static void DoNothing(this ClassType self, bool redraw)
    {
    }
    public static void DoNothing2(this ClassType self, bool redraw, object ano)
    {
    }
}
```

### Details
original code was much longer and more complex, but have reduced to bare minimum.
Further, note that if the Import is absent (i.e. at project level), then the attributes are converted in place, and the "this" keyword is NOT added.

**Comment by GrahamTheCoder** [comment]
The additional `this` is fixed in the release that just happened (apologies for the unfortunate timing). Your example works on the [online converter](https://roslyncodeconverter.azurewebsites.net/). If you use the [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter) would you mind updating and letting me know if it works with your full example?

I don't believe I've fixed the second issue you mention. Do you mean that if the Import is absent at the project level and is present at the file level, or absent at both, presumably causing the Visual Basic not to compile?

Thanks for the help!

**Comment by RachelDavids** [comment]
My original VB compiles OK.
I suspect I had a file level import.
If I remove the file level import  in the sample above, we get the failure mentioned (attributes not converted)

**Comment by RachelDavids** [comment]
will retry when I get home (from work) this evening

**Comment by GrahamTheCoder** [comment]
The web converter doesn't have a global import for `System.Runtime.CompilerServices`, but it might be a good idea for me to add one since it's probably quite common. In fact, I'll put a todo here for:
* [ ] Look at a few VB projects around the web and find any common (BCL) global imports to add

If you have a case where it still doesn't work, please let me know whether the import is global or file-level. Thanks for your help!

**Comment by GrahamTheCoder** [comment]
Thanks for checking,that's great news! I've opened another issue to track the above todo.
