### ISSUE TITLE
VB -> C#: problems with pulling variables out of scope

### ISSUE THREAD

**Issue by KunzeAndreas** [icsharpcode/CodeConverter#913]
### VB.Net input code
```vbnet
Private Shared Sub ProblemsWithPullingVariablesOut()
      ' example 1
      For Each a In New List(Of String)
          Dim b As Long
          If a = "" Then
              b = 1
          End If
          DoSomeImportantStuff()
      Next

      ' example 2
      Dim c As String
      Do While True
          Dim d As Long
          If c = "" Then
              d = 1
          End If

         DoSomeImportantStuff()
         Exit Do
     Loop
 End Sub
 Private Shared Sub DoSomeImportantStuff()
     Debug.Print("very important")
 End Sub
```

### Erroneous output
```C#
 // example 1
        private static void ProblemsWithPullingVariablesOut()
        {
            ;

            // example 2
            var c = default(string);
            ;
        }
        private static void DoSomeImportantStuff()
        {
            Debug.Print("very important");
        }
```

### Details
* Product in use: VS extension
* Version in use: 9.0.1.0
* Did you see it working in a previous version, which? yes (8.5)

**Comment by GrahamTheCoder** [comment]
Oh dear, that looks pretty broken 😲

**Comment by GrahamTheCoder** [comment]
I think I can see the problem - it has a null initializer. I'll try to put in a quick fix now

**Comment by Yozer** [comment]
@GrahamTheCoder I guess we're doing some kind of data flow analysis to see if local variables are always assigned before read.
I wonder if the logic "pull variables before the loop" can be skipped when the initializer in C# is null.
In these examples, I think it's safe to declare ```b``` and ```d``` inside a loop.

**Comment by GrahamTheCoder** [comment]
I like the general idea of not pulling out variables when it isn't needed. But the mechanism - making decisions based on the C# syntax tree - is *usually* a bad idea. You can never know exactly why it ended up that way. It may well be due to sensible flow analysis, or it could just be a style preference. I don't know in this case if any analysis takes into account this possibility properly. I'd rather re-do the analysis (even calling the same method) at the point we expect something particular of it for clarity if needed and not in the same method.

**Comment by KunzeAndreas** [comment]
Thank you for the quick fix, I will try this in the next few days on our codebase.
