### ISSUE TITLE
C# -> VB: Properties with a modifer are being converted to auto properties

### ISSUE THREAD

**Issue by RussellSmith2** [icsharpcode/CodeConverter#92]
### Input code
```C#
public string Text { get; private set; }
```

### Erroneous output
```vbnet
Public Property Text As String
```

### Expected output
```vbnet
Private _Text As String

Public Property Text As String
    Get
        Return _Text
    End Get
    Private Set(ByVal value As String)
        _Text = value
    End Set
End Property
```

### Details
Product in use: both

Version in use: 5.6.3

HasNoAccessorBody in VB\NodesVisitor.cs needs updated to check for modifiers on accessors.

**Comment by BrianFreemanAtlanta** [comment]
I started to look into this issue.  There are 2 albeit related issues.
1. The stated `HasNoAccessorBody` corrections (and adding accessor/declaration for VB code)
2. Separate modifiers for get/set routines

Fixing task 1 the results will be:
```vb
Private _Text As String

Public Property Text As String
    Get
        Return _Text
    End Get
    Set(ByVal value As String)
        _Text = value
    End Set
End Property
```
With the missing modifier for the `Set` routine.
I looked at the reverse translation and the code doesn't handle the different modifiers from VB -> C# either.
Should I open a separate issue for task 2 and do a pull request on it before completing this?  Or see if a simple solution for task 2 can be done as part of this issue?

**Comment by GrahamTheCoder** [comment]
I don't have good Internet access to look into the specific case right now,
but what you said makes sense. Feel free to combine related things together
if they are small and similar priority/risk to save bureacracy, so long as
the pr makes clear what it's trying to achieve. Try to at least keep them
in separate commits where possible so that if necessary they could be
easily separately merged.

**Comment by GrahamTheCoder** [comment]
I think there may be another open issue to deal with modifiers more
generally using the CsSyntaxGenerator.

**Comment by GrahamTheCoder** [comment]
In future we might consider specialising the case of a private setter since VB provides a more idiomatic way to write to the backing field of a readonly property. If anyone wants to open this as a separate enhancement, feel free, I'm just leaving it here now for completeness:

```csharp
public string Value {get; private set;}
```

```vbnet
Public ReadOnly Property Value As String
```

Within the class it's possible to use the private setter by using an underscore prefix: `_Value = "Fred"`
