### ISSUE TITLE
How about some convert to F# lovin? 

### ISSUE THREAD

**Issue by WillEhrendreich** [icsharpcode/CodeConverter#923]
**Is your feature request related to a problem? Please describe.**
If I could live in purely fsharp focused coding world, I'd be thrilled, I find both vb and cs too verbose, and while I can and have been translating manually into fsharp, a quick conversion process would make this whole thing so much nicer. 

**Describe the solution you'd like**
even a very crude version of what works in vb and cs now. even if it doesn't do it perfectly, I'm fine, I can happily refactor all of it into more idiomatic fsharp, but it would go a long way in the process if it could spit out even very ugly but workable code. 

**Describe alternatives you've considered**
[This project seems to be doing something with this idea](https://github.com/willsam100/FShaper)
I've tried to use it, but it freaks out and complains about syntax errors, when there is no syntax error present in my file..

**Comment by GrahamTheCoder** [comment]
Hello, that does sound like a cool project, and there is likely a bunch of code in this repo that would help, at least in terms of context. Here are some things to be aware of:
* Accurate code conversion is hard. VB and C# appear very close in structure and syntax, yet accurately representing one in the other often leads to messy non-idiomatic code in the other. Converting C# to F# accurately would likely give you reasonably poor quality F#. e.g. You will have object-oriented F#, not functional-style F#. Lots of people like F# because their 15 lines of F# would need hundreds of lines of C#. An accurate converter will (in the vast majority of cases) be taking hundreds of lines of C# and producing hundreds of lines of F# (though occasionally you may be able to detect a pattern than can be condensed).
* You'd need to find/create a syntax tree manipulation library for F#. Roslyn has SyntaxFactory for both VB and C#, which makes it quite easy to incrementally build the output then write it to a file, I'm unaware of any equivalent for F#, but would strongly advise using one rather than trying to work with strings directly like this  [stack overflow answer](https://stackoverflow.com/a/60327293) attempted. Some other project [like this](https://github.com/fsharp/FsAutoComplete/blob/main/src/FsAutoComplete.Core/CodeGeneration.fs) might have something you can work from.
* You will need to have/develop a very good understanding of both C# and F# to succeed - I haven't worked with F# much so can't advise on any particularly tricky details here. An example from this converter, would be figuring out how to represent VB's nullable bool logic concisely without changing the semantics (e.g. execution order in various cases). https://github.com/icsharpcode/CodeConverter/issues/894

I'll close the issue in this repo since it's certainly sufficiently big and complicated to deserve its own repo, but I'm very happy to continue discussion here or hear about any further work. To get started I'd suggest creating a class that looks a bit like https://github.com/icsharpcode/CodeConverter/blob/master/CodeConverter/VB/MethodBodyExecutableStatementVisitor.cs, and writing some tests like this: https://github.com/icsharpcode/CodeConverter/blob/master/Tests/VB/StatementTests.cs
