### ISSUE TITLE
VB -> C#: Inconsistent usage of `ToString()`, strange `Operations.AddObject()`

### ISSUE THREAD

**Issue by Saibamen** [icsharpcode/CodeConverter#940]
### VB.Net input code
```vbnet
For intN = 1 To intLochMenge
    my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
Next

For intN = 1 To 10
    my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
Next

my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
```

### Erroneous output
```C#
for (int intN = 1, loopTo = intLochMenge; intN <= loopTo; intN++)
    my_function("-" + Conversions.ToString(intN) + "-", "-" + Conversions.ToString(Operators.AddObject(intN, 1)) + "-");

for (int intN = 1; intN <= 10; intN++)
    my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");

my_function("-" + intN + "-", "-" + (intN + 1) + "-");
```

### Expected output
```C#
for (int intN = 1, loopTo = intLochMenge; intN <= loopTo; intN++)
    my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");

for (int intN = 1; intN <= 10; intN++)
    my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");

my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");
```

### Details
* Product in use: [icsharpcode.github.io/CodeConverte](https://icsharpcode.github.io/CodeConverter/)
* Version in use: 9.0.3.0

**Comment by Yozer** [comment]
@Saibamen VB.Net input code doesn't seem to be complete. It's missing definition for ```intLochMenge```.
My guess is that the converter treats ```intLochMenge``` and ```intN``` as ```System.Object```. 
If you declare ```intLochMenge``` correctly the conversion will be more accurate:
```vbnet
Public Sub Test(intLochMenge as Integer)
  For intN = 1 To intLochMenge
      my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
  Next
  
  For intN = 1 To 10
      my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
  Next
  
  my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
End Sub
```

The reason is that ```Operators.AddObject``` works for everything including cases where we have overloaded operators for custom objects: [sharplab.io](https://sharplab.io/#v2:DYLgbgRgNAJiDUAfAkgWwA4HsBOAXAzgAQDKAnvrgKaoCwAUGlnkWRdQHQDCmwwlAxrgCWmAHb52AcUqjK2If3r0ACgFcIwBYQCymGKr469BygEZ6hSyXU6AhkNEAKAJQWr7gCqUKjgHKUAd0IvCk5gW3x8RwAmZ1c6dwBRURhrCCUEq2IbENxHB1wAGUx+AAttGQBzSkIIwgB5CAArAVx493cAMRxCAt9CAF5CU2DMXtEikvKqyjcOju5xHkp2AHV5KkKHSkd8if74YedCADJCACIAWnP2+cJ/AA9cOcJk1Oz0ujejfT4MtQ0WjCESIuWBkRejD4qBkBEIyG4GFs2FsGh29QAZsFvLhwfhbpZlPIwLYqIQAEqUWwweqiYCkQgAfQetSIyAmlGq2BeAM0/DS90CjhZAEE2RyuQSOszBoQHi9vh8Mu5eVpiKVkZRUqshDAZA5Kg10HJST1OB5SMbHOgRmL4RK5Mc7WDwhDMvNKbhVNhRIKgi6QdbTFLvvVjSjcDhlVZVfzOqpRIIRL7EehNR5MI5MLhSnJCM6cXineKqFz4RhobC2ankai+I5MdjQq78VxMEjsJQMy93MgsZSMXIZPxKIkAI6qWzAKIVKCEbO57DHDy532e72+gAMPasffnObzyCIvgXBuCq4plC9PuGO8s65vzLbHa7mYXcnYzJDKUI8cTwjEaNCXUPkSA1TtUjDE1I2wQgAB5HD4DFcHzUFCxbOd5EqUoUILZsQWLQgACFMGWWxRDvS9rxTds007WCGyxANImcdgAG0ABFKAxWwDFwABdZ86J2JDcEwoRsLaeDCG3d1Xh/KCIyjOgeRAtVwK1I1oJ6AA+RDuNwtD8MicTJNQptcRbQiSLIii5PcB8aJfBjG2Y1tOO43jgAEoTNX05DTJw44dJkhUFPDU1uRUuTYzAzVIIimD4IGfzDIsvFArStzrNIvhyMoxzCBrejCEY9KrPYrieL4wTipEgzMuOOChlkpJwu0qLVMBfl1XirSlNgnSUtE8y3My0b0II8ybLyuy7iojcitozUXKYyaWMqzyat8ztUsawghtCuTQ0S5SutA3qIP6yLTlSibjPwca7WIXB5FESpCJet7KgKq9FtE9gMy+g0XFOQgsJwsKEo6oDCFiy7NMUm74EcWx7sskE50o+acfcCB0aLAmW1+6i/XKwNbE/FlDggKnv2hgbzvUvqkaSy5UaJzHCGx3HcfxvCMZYzm3Xmwr/H9daokpmVLkIWmvyh66YNh2L6jAOR5D1Ig/yTMRRmB97Qee16DRJxanyBk3Dfp38E11uzvjxIA)
Since in your input type of ```intLochMenge``` is unknown (it can be everything) it's safer to use ```Operators.AddObject``` and ```Conversions.ToString```

**Comment by Saibamen** [comment]
Ok, but for this input:

```vbnet
Public Sub Test(intLochMenge as Integer)
  Dim intLochMenge As Integer
  intLochMenge = 10

  For intN = 1 To intLochMenge
      my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
  Next
  
  For intN = 1 To 10
      my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
  Next
  
  my_function("-" & CStr(intN) & "-", "-" & CStr(intN + 1) & "-")
End Sub
```

I still get inconstant `ToString()` usage:

```C#
public void Test(int intLochMenge)
{
    int intLochMenge;
    intLochMenge = 10;

    for (int intN = 1, loopTo = intLochMenge; intN <= loopTo; intN++)
        my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");

    for (int intN = 1; intN <= 10; intN++)
        my_function("-" + intN.ToString() + "-", "-" + (intN + 1).ToString() + "-");

    my_function("-" + intN + "-", "-" + (intN + 1) + "-");
}

```

See `my_function` inside for loop and outside

**Comment by GrahamTheCoder** [comment]
I'm afraid incomplete input is an unsolvable problem in general, so the compiler and the converter make a best effort with what they've got. It's not obvious to me exactly what's causing each case, but if you use compilable code (e.g. dim intn as integer at the top) you'll find the behaviour greatly improves.

Conversion aside, you can quickly explore how the compiler sees snippets using sharplab if you're interested 
https://sharplab.io/#v2:DYLgbgRgNALiCGBnGUAmIDUAfADgVwmAEsBjAAhOCUQrIFgAofQ0sxAsgWwAoBKRsoKGDGAMQD2AJzJEAdjAByZALxkAjGQAq4mfIAy4kgAsAsgFNZAczMChnAJ4B9AGZ5ZJGEXGzuDgMowknKWUGQARAC0YWQAZGQAwgGS3HKKvLHhUaGR0XGJgSnyShjq6XE5/AwKZgAeMIxiUrqKKupaOmoADLaCDi5uHl4+/oHB2VEZ+cmpCmWZYeO5CUmFLSVqcxWM1XUNDH2u7p7evvZJY/OTKzObWZd510Vk67dhlYwWqGwEH7JflNQyEA===

One possible future direction for this would be to create a layer which tries applying various fixes to make input compilable before it gets to the main conversion.e.g. declaring variables and methods. This would be a major undertaking and probably work best as a standalone library that the converter can just call at the start, so I'll close this issue for now but feel free to open an issue to track integrating such a library if it is found/created.

If you have a compilable snippet exhibiting unusual behaviour please feel free to reopen if closely related, or open a new issue. Thanks!
