### ISSUE TITLE
VB -> C#: Infinite While loop inside For loop

### ISSUE THREAD

**Issue by Korfu** [icsharpcode/CodeConverter#946]
### VB.Net input code
```vb 
For Each appRole In accessingUnit.Role.ApplicationRoles
    Dim objectUnit = Company.GetInstance(appRole.ObjectId.Value)
    While objectUnit IsNot Nothing
        If CBool(unit.UnitType And HrUnitTypeEnum.CanHaveEmployment) Then
            If unit.Id = objectUnit.Id Then
                Return True
            Else
                Continue For
            End If
        End IF
        objectUnit = objectUnit.ParentCompany
    End While
Next
```

### Erroneous output
```C#
Converter tool would translate `Continue For` into `continue`.
```

### Expected output
```C#
Converter tool should translate `Continue For` into `break`. It should exit the outer `for loop` and instead it was endleslly starting over and over again the `inner while loop`.
```

### Details
* The inner `while loop` has become an infinite loop. 
* We converted gigantic monolith (1.3 million lines of code) and were stuck with this issue for a couple of days. Caused serious performance issues.

**Comment by GrahamTheCoder** [comment]
Thanks for the clear report. Should be straightforward to fix since the logic needed in VisitContinueStatement can likely mimic parts of VisitExitStatement:
https://github.com/icsharpcode/CodeConverter/blob/c5e640500375d93ccafb055a9254d18c2070cb53/CodeConverter/CSharp/MethodBodyExecutableStatementVisitor.cs#L434-L472
https://github.com/icsharpcode/CodeConverter/blob/c5e640500375d93ccafb055a9254d18c2070cb53/CodeConverter/CSharp/PerScopeState.cs#L192-L205

Tests here: https://github.com/icsharpcode/CodeConverter/blob/da720fa0549dc7e121fe6d3dcb0eb19f8d756d16/Tests/CSharp/StatementTests/ExitableMethodExecutableStatementTests.cs
