### ISSUE TITLE
VB - > C#: Conversion code style

### ISSUE THREAD

**Issue by ortrails** [icsharpcode/CodeConverter#980]
CInt(myString) gets converted to Conversions.ToInteger(myString). Should be: Convert.ToInt32(myString).

CBool(myString) gets converted to Conversions.ToBoolean(myString) ? 1 : 0. Should be: Convert.ToBoolean(myString).

"If objProd IsNot Nothing And objDev IsNot Nothing" gets converted to "if objProd is not null and objDev is not null". Should be "if (objProd!= null & objDev!= null)"

### Details
* VS extension
* Version in use: 9.1.1.0

**Comment by GrahamTheCoder** [comment]
Hi there, thanks for the feedback. If you're interested, there are some [guidelines here](https://github.com/icsharpcode/CodeConverter/blob/1eef0d75b490d881093e18cce4e14f98c906e244/.github/CONTRIBUTING.md#deciding-what-the-output-should-be) which I use to guide and prioritise decisions like these. Most crucially, behaving the same at runtime is top of the list.

Because CInt("5.2") returns 5, we couldn't just use Convert.ToInt32("5.2") since that would [throw a formatexception for example](https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACgCSyqBZASwDG8YuWIAzGADoAan3KIAhsABCC8oMkBhYkT7BG8agbCDG5duwAKiCMEGVNwNVU0W2lD5Wu371ABYK8IxoNDaUPAp8yAAUAJTsnokOxMii+pIA6vB8TAAyUYzRmrjIMNEARACskgBM5bHx7kke2qnE6Vk5jPnIha1gBuop5JIAKsQlTADmBhXVdQ0JzcltHdl5BUUpA2RjE6UAzDVztfWNiQCiyCHUNuxXIY7OQA===) The same goes for [ToBoolean](https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACgCSyqBZASwDG8YuWIAzGADoAan3KIAhsABCC8oMkBhYkT7BG8agbCDG5duwAKiCMEGVNwNVU0W2lD5Wu371ABYK8IxoNDaUPAp8yAAUAJTsnokOxMii+pIA6vB8TAAyUYzRmsrExMDRAEQArJIATBWx8e5JHtqpZYyZ2XkFRSlgBuop5JIAKsQlHQox1XUNTS2twx1dOYz5yIVtA2RjE6X605U19Y0JngCiyCHUNuxXIY7OQA===)

In the case of equality, consider: [Input](https://sharplab.io/#v2:DYLgbgRgNALiBOBXAdlAJiA1AHwJIFsAHAe3hgGcACAZQE9yYBTfAWACh2AFRCYASwDGlAMLAAhuSrD27SnMrdegmgAsx8Rmho9KAWTF9kACgCUs+RYAiffJWIQAVp3jEtAXkoA5RgHcR5izlrW3sHS0YwSg8vX382QPlcADM7R2dXSlxyT2IYL1yVQwBzSgBBZC1Q8MisnLy6wuQSgBUVRmQRYmRyYmBGADoAdXg+JgAZQ0YjACJrLWRcykRyRjswRnhgYjE0cmmTSgB9AMCAUWAVzu7egeHRxgnkKemAVRXK9c3t3f2T04rtBAZPEEgoePwhNQ1BotAB5QgbMQwUgeIwAIVoADUxMBKAIAIxlKRQSgY7G4gQAJiJIgOpSoaOINzEyBOFgASowYIh4B0AGI4lZ/AHwxHI+DAiyKCGqdSaSii+BI0gAHgAfJR0VicXjCfSRCSyTqqTThHSGUy+iy2fJOdzeZQBRdGMK4QileL2P8tKIJOQgA), [Current output](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLACgACAmAjBjTAZgAIAHAQzGAEsKAbEnEgYQwG8D0SentsMvEp25DeANyokA9gCMAVgAUw0uCQC8JKAFMA7qwAUASgDcgsT0lgZCgCLbxGrXsOnzFmgDMSBuUpVqNADOWtLAWhD0jABkNvL2jsGh4VCR9EbuFryYuACcBgBEtjRqUGEkEEHaMuLaYPTSFHBBBW6iFtr0VZlZTHmFAKpVatK19Y3NrWbtJAC+XELEfQBsJLLS0ozSZHUUwNLW6uoGLCQAxrgwrOfYGTMivZgA7CSeDFXTQvPomUs5q+tNjIdmA9gcSABCY6nC5XGG3TIPLLPV7vbSfXjfWZAA=), [your suggested output](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwLACgACAmAjBjTAZgAIAHAQzGAEsKAbEnEgYQwG8D0SentsMvEp25DeANyokA9gCMAVgAUw0uCQC8JKAFMA7qwAUASgDcgsT0lgZCgCLbxGrXsOnzFmgDMSBuUpVqAISaUBD0jABkNvL2jsFaYfRG7ha8mLgAnAYARLY0alDSwCQQAM7aMuLaYPTSFHCl2W6iFtr05SmpTJk5AKrlatJVNXUNTWYtJAC+XELE3QBsJLLS0ozSZNUUwNLW6uoGLCQAxrgwrCfYyZMiXZgA7CSeDOUTQjPoKfPpSytrMpswNtdiRgocTmcLscrilbqkHk8Xto3rwPlMgA===)
I think it's fair to say that someone overloading an equality operator incorrectly is reasonably rare, so if your suggested code was fantastically better by some other metric (e.g. one of the other guidelines) I'd consider it, or indeed, we could do some analysis, and when absolutely certain the equality operators aren't overloaded, use your suggestion.

Personally, I'm of the mind that the current output is superior in one way: it can be 100% known from reading it what it will do rather than 99.99% known. This is why I tend to use it in code I write. The downside is that it's newer syntax which not everyone will be so familiar with which counts against it. It will likely become more common over time though, so I don't see this as a big impetus to make a change here since it's mainly a style preference, which can always be changed with an automated refactoring tool after conversion.

I hope that makes sense. Thanks,
Graham.

**Comment by ortrails** [comment]
Graham, thanks for getting back to me. Makes a lot of sense.
Andrew
