### ISSUE TITLE
Support ARM64 version of the extension

### ISSUE THREAD

**Issue by andriysavin** [icsharpcode/CodeConverter#989]
Hello, I'm using VS2022 on Arm, and would like to have this extension working on this architecture.

**Comment by GrahamTheCoder** [comment]
Hi, thanks for getting in touch. It looks like it may be reasonably simple set of tweaks to the build configuration:
https://learn.microsoft.com/en-us/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022
If someone with an ARM device to test on wants to try that and PR it if it works that'd be great. Otherwise I'll try to have a go at some point and hope for the best.

**Comment by andriysavin** [comment]
@GrahamTheCoder I've just noticed your pull request while was finishing the change myself :) anyway, it was an interesting journey to dive a bit in new area of development! Thanks!
